// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reckon_snapshots.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SourceUuid    string                 `protobuf:"bytes,2,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	StreamUuid    string                 `protobuf:"bytes,3,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSnapshotRequest) Reset() {
	*x = RecordSnapshotRequest{}
	mi := &file_reckon_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSnapshotRequest) ProtoMessage() {}

func (x *RecordSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RecordSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *RecordSnapshotRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *RecordSnapshotRequest) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *RecordSnapshotRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

func (x *RecordSnapshotRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecordSnapshotRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ReadSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SourceUuid    string                 `protobuf:"bytes,2,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	StreamUuid    string                 `protobuf:"bytes,3,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSnapshotRequest) Reset() {
	*x = ReadSnapshotRequest{}
	mi := &file_reckon_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSnapshotRequest) ProtoMessage() {}

func (x *ReadSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSnapshotRequest.ProtoReflect.Descriptor instead.
func (*ReadSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSnapshotRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadSnapshotRequest) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *ReadSnapshotRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

func (x *ReadSnapshotRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SourceUuid    string                 `protobuf:"bytes,2,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	StreamUuid    string                 `protobuf:"bytes,3,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_reckon_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSnapshotRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

func (x *DeleteSnapshotRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SourceUuid    string                 `protobuf:"bytes,2,opt,name=source_uuid,json=sourceUuid,proto3" json:"source_uuid,omitempty"`
	StreamUuid    string                 `protobuf:"bytes,3,opt,name=stream_uuid,json=streamUuid,proto3" json:"stream_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_reckon_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *ListSnapshotsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ListSnapshotsRequest) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *ListSnapshotsRequest) GetStreamUuid() string {
	if x != nil {
		return x.StreamUuid
	}
	return ""
}

type ListAllSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllSnapshotsRequest) Reset() {
	*x = ListAllSnapshotsRequest{}
	mi := &file_reckon_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllSnapshotsRequest) ProtoMessage() {}

func (x *ListAllSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListAllSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{4}
}

func (x *ListAllSnapshotsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type RecordSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSnapshotResponse) Reset() {
	*x = RecordSnapshotResponse{}
	mi := &file_reckon_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSnapshotResponse) ProtoMessage() {}

func (x *RecordSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RecordSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{5}
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_reckon_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{6}
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotRecord      `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_reckon_snapshots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_snapshots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_snapshots_proto_rawDescGZIP(), []int{7}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotRecord {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_reckon_snapshots_proto protoreflect.FileDescriptor

const file_reckon_snapshots_proto_rawDesc = "" +
	"\n" +
	"\x16reckon_snapshots.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"\xbe\x01\n" +
	"\x15RecordSnapshotRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vsource_uuid\x18\x02 \x01(\tR\n" +
	"sourceUuid\x12\x1f\n" +
	"\vstream_uuid\x18\x03 \x01(\tR\n" +
	"streamUuid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\"\x8c\x01\n" +
	"\x13ReadSnapshotRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vsource_uuid\x18\x02 \x01(\tR\n" +
	"sourceUuid\x12\x1f\n" +
	"\vstream_uuid\x18\x03 \x01(\tR\n" +
	"streamUuid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"\x8e\x01\n" +
	"\x15DeleteSnapshotRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vsource_uuid\x18\x02 \x01(\tR\n" +
	"sourceUuid\x12\x1f\n" +
	"\vstream_uuid\x18\x03 \x01(\tR\n" +
	"streamUuid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"s\n" +
	"\x14ListSnapshotsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vsource_uuid\x18\x02 \x01(\tR\n" +
	"sourceUuid\x12\x1f\n" +
	"\vstream_uuid\x18\x03 \x01(\tR\n" +
	"streamUuid\"4\n" +
	"\x17ListAllSnapshotsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\x18\n" +
	"\x16RecordSnapshotResponse\"\x18\n" +
	"\x16DeleteSnapshotResponse\"X\n" +
	"\x15ListSnapshotsResponse\x12?\n" +
	"\tsnapshots\x18\x01 \x03(\v2!.reckon.gateway.v1.SnapshotRecordR\tsnapshots2\x88\x04\n" +
	"\x0fSnapshotService\x12e\n" +
	"\x0eRecordSnapshot\x12(.reckon.gateway.v1.RecordSnapshotRequest\x1a).reckon.gateway.v1.RecordSnapshotResponse\x12Y\n" +
	"\fReadSnapshot\x12&.reckon.gateway.v1.ReadSnapshotRequest\x1a!.reckon.gateway.v1.SnapshotRecord\x12e\n" +
	"\x0eDeleteSnapshot\x12(.reckon.gateway.v1.DeleteSnapshotRequest\x1a).reckon.gateway.v1.DeleteSnapshotResponse\x12b\n" +
	"\rListSnapshots\x12'.reckon.gateway.v1.ListSnapshotsRequest\x1a(.reckon.gateway.v1.ListSnapshotsResponse\x12h\n" +
	"\x10ListAllSnapshots\x12*.reckon.gateway.v1.ListAllSnapshotsRequest\x1a(.reckon.gateway.v1.ListSnapshotsResponseBAZ?github.com/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_snapshots_proto_rawDescOnce sync.Once
	file_reckon_snapshots_proto_rawDescData []byte
)

func file_reckon_snapshots_proto_rawDescGZIP() []byte {
	file_reckon_snapshots_proto_rawDescOnce.Do(func() {
		file_reckon_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_snapshots_proto_rawDesc), len(file_reckon_snapshots_proto_rawDesc)))
	})
	return file_reckon_snapshots_proto_rawDescData
}

var file_reckon_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_reckon_snapshots_proto_goTypes = []any{
	(*RecordSnapshotRequest)(nil),   // 0: reckon.gateway.v1.RecordSnapshotRequest
	(*ReadSnapshotRequest)(nil),     // 1: reckon.gateway.v1.ReadSnapshotRequest
	(*DeleteSnapshotRequest)(nil),   // 2: reckon.gateway.v1.DeleteSnapshotRequest
	(*ListSnapshotsRequest)(nil),    // 3: reckon.gateway.v1.ListSnapshotsRequest
	(*ListAllSnapshotsRequest)(nil), // 4: reckon.gateway.v1.ListAllSnapshotsRequest
	(*RecordSnapshotResponse)(nil),  // 5: reckon.gateway.v1.RecordSnapshotResponse
	(*DeleteSnapshotResponse)(nil),  // 6: reckon.gateway.v1.DeleteSnapshotResponse
	(*ListSnapshotsResponse)(nil),   // 7: reckon.gateway.v1.ListSnapshotsResponse
	(*SnapshotRecord)(nil),          // 8: reckon.gateway.v1.SnapshotRecord
}
var file_reckon_snapshots_proto_depIdxs = []int32{
	8, // 0: reckon.gateway.v1.ListSnapshotsResponse.snapshots:type_name -> reckon.gateway.v1.SnapshotRecord
	0, // 1: reckon.gateway.v1.SnapshotService.RecordSnapshot:input_type -> reckon.gateway.v1.RecordSnapshotRequest
	1, // 2: reckon.gateway.v1.SnapshotService.ReadSnapshot:input_type -> reckon.gateway.v1.ReadSnapshotRequest
	2, // 3: reckon.gateway.v1.SnapshotService.DeleteSnapshot:input_type -> reckon.gateway.v1.DeleteSnapshotRequest
	3, // 4: reckon.gateway.v1.SnapshotService.ListSnapshots:input_type -> reckon.gateway.v1.ListSnapshotsRequest
	4, // 5: reckon.gateway.v1.SnapshotService.ListAllSnapshots:input_type -> reckon.gateway.v1.ListAllSnapshotsRequest
	5, // 6: reckon.gateway.v1.SnapshotService.RecordSnapshot:output_type -> reckon.gateway.v1.RecordSnapshotResponse
	8, // 7: reckon.gateway.v1.SnapshotService.ReadSnapshot:output_type -> reckon.gateway.v1.SnapshotRecord
	6, // 8: reckon.gateway.v1.SnapshotService.DeleteSnapshot:output_type -> reckon.gateway.v1.DeleteSnapshotResponse
	7, // 9: reckon.gateway.v1.SnapshotService.ListSnapshots:output_type -> reckon.gateway.v1.ListSnapshotsResponse
	7, // 10: reckon.gateway.v1.SnapshotService.ListAllSnapshots:output_type -> reckon.gateway.v1.ListSnapshotsResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reckon_snapshots_proto_init() }
func file_reckon_snapshots_proto_init() {
	if File_reckon_snapshots_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_snapshots_proto_rawDesc), len(file_reckon_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_snapshots_proto_goTypes,
		DependencyIndexes: file_reckon_snapshots_proto_depIdxs,
		MessageInfos:      file_reckon_snapshots_proto_msgTypes,
	}.Build()
	File_reckon_snapshots_proto = out.File
	file_reckon_snapshots_proto_goTypes = nil
	file_reckon_snapshots_proto_depIdxs = nil
}
