// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_health.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_Check_FullMethodName                     = "/reckon.gateway.v1.HealthService/Check"
	HealthService_Health_FullMethodName                    = "/reckon.gateway.v1.HealthService/Health"
	HealthService_VerifyClusterConsistency_FullMethodName  = "/reckon.gateway.v1.HealthService/VerifyClusterConsistency"
	HealthService_VerifyMembershipConsensus_FullMethodName = "/reckon.gateway.v1.HealthService/VerifyMembershipConsensus"
	HealthService_CheckRaftLogConsistency_FullMethodName   = "/reckon.gateway.v1.HealthService/CheckRaftLogConsistency"
	HealthService_GetMemoryLevel_FullMethodName            = "/reckon.gateway.v1.HealthService/GetMemoryLevel"
	HealthService_GetMemoryStats_FullMethodName            = "/reckon.gateway.v1.HealthService/GetMemoryStats"
	HealthService_GetServerInfo_FullMethodName             = "/reckon.gateway.v1.HealthService/GetServerInfo"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HealthService provides health checking and cluster diagnostics.
type HealthServiceClient interface {
	// Quick health check for a specific store.
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Overall gateway health (all stores).
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Verify cluster consistency for a store.
	VerifyClusterConsistency(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error)
	// Verify membership consensus across cluster nodes.
	VerifyMembershipConsensus(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error)
	// Check Raft log consistency.
	CheckRaftLogConsistency(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error)
	// Get memory pressure level for a store.
	GetMemoryLevel(ctx context.Context, in *MemoryLevelRequest, opts ...grpc.CallOption) (*MemoryLevelResponse, error)
	// Get detailed memory statistics for a store.
	GetMemoryStats(ctx context.Context, in *MemoryStatsRequest, opts ...grpc.CallOption) (*MemoryStatsResponse, error)
	// Get server / store configuration including the tamper-resistance
	// algorithm identifier the client must use to verify chain
	// hashes locally. Added in reckon-gateway 0.2.0.
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HealthService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) VerifyClusterConsistency(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_VerifyClusterConsistency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) VerifyMembershipConsensus(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_VerifyMembershipConsensus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) CheckRaftLogConsistency(ctx context.Context, in *ClusterCheckRequest, opts ...grpc.CallOption) (*ClusterCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterCheckResponse)
	err := c.cc.Invoke(ctx, HealthService_CheckRaftLogConsistency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetMemoryLevel(ctx context.Context, in *MemoryLevelRequest, opts ...grpc.CallOption) (*MemoryLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryLevelResponse)
	err := c.cc.Invoke(ctx, HealthService_GetMemoryLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetMemoryStats(ctx context.Context, in *MemoryStatsRequest, opts ...grpc.CallOption) (*MemoryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryStatsResponse)
	err := c.cc.Invoke(ctx, HealthService_GetMemoryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, HealthService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations should embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// HealthService provides health checking and cluster diagnostics.
type HealthServiceServer interface {
	// Quick health check for a specific store.
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Overall gateway health (all stores).
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Verify cluster consistency for a store.
	VerifyClusterConsistency(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error)
	// Verify membership consensus across cluster nodes.
	VerifyMembershipConsensus(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error)
	// Check Raft log consistency.
	CheckRaftLogConsistency(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error)
	// Get memory pressure level for a store.
	GetMemoryLevel(context.Context, *MemoryLevelRequest) (*MemoryLevelResponse, error)
	// Get detailed memory statistics for a store.
	GetMemoryStats(context.Context, *MemoryStatsRequest) (*MemoryStatsResponse, error)
	// Get server / store configuration including the tamper-resistance
	// algorithm identifier the client must use to verify chain
	// hashes locally. Added in reckon-gateway 0.2.0.
	GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfoResponse, error)
}

// UnimplementedHealthServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHealthServiceServer) VerifyClusterConsistency(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyClusterConsistency not implemented")
}
func (UnimplementedHealthServiceServer) VerifyMembershipConsensus(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyMembershipConsensus not implemented")
}
func (UnimplementedHealthServiceServer) CheckRaftLogConsistency(context.Context, *ClusterCheckRequest) (*ClusterCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRaftLogConsistency not implemented")
}
func (UnimplementedHealthServiceServer) GetMemoryLevel(context.Context, *MemoryLevelRequest) (*MemoryLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemoryLevel not implemented")
}
func (UnimplementedHealthServiceServer) GetMemoryStats(context.Context, *MemoryStatsRequest) (*MemoryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemoryStats not implemented")
}
func (UnimplementedHealthServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedHealthServiceServer) testEmbeddedByValue() {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_VerifyClusterConsistency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).VerifyClusterConsistency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_VerifyClusterConsistency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).VerifyClusterConsistency(ctx, req.(*ClusterCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_VerifyMembershipConsensus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).VerifyMembershipConsensus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_VerifyMembershipConsensus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).VerifyMembershipConsensus(ctx, req.(*ClusterCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_CheckRaftLogConsistency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).CheckRaftLogConsistency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_CheckRaftLogConsistency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).CheckRaftLogConsistency(ctx, req.(*ClusterCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetMemoryLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetMemoryLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetMemoryLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetMemoryLevel(ctx, req.(*MemoryLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetMemoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetMemoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetMemoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetMemoryStats(ctx, req.(*MemoryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _HealthService_Health_Handler,
		},
		{
			MethodName: "VerifyClusterConsistency",
			Handler:    _HealthService_VerifyClusterConsistency_Handler,
		},
		{
			MethodName: "VerifyMembershipConsensus",
			Handler:    _HealthService_VerifyMembershipConsensus_Handler,
		},
		{
			MethodName: "CheckRaftLogConsistency",
			Handler:    _HealthService_CheckRaftLogConsistency_Handler,
		},
		{
			MethodName: "GetMemoryLevel",
			Handler:    _HealthService_GetMemoryLevel_Handler,
		},
		{
			MethodName: "GetMemoryStats",
			Handler:    _HealthService_GetMemoryStats_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _HealthService_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reckon_health.proto",
}
