// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reckon_health.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_HEALTHY   HealthStatus = 0
	HealthStatus_HEALTH_STATUS_DEGRADED  HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_HEALTHY",
		1: "HEALTH_STATUS_DEGRADED",
		2: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_HEALTHY":   0,
		"HEALTH_STATUS_DEGRADED":  1,
		"HEALTH_STATUS_UNHEALTHY": 2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_health_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_reckon_health_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{0}
}

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_HEALTHY     ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_DEGRADED    ClusterStatus = 1
	ClusterStatus_CLUSTER_STATUS_SPLIT_BRAIN ClusterStatus = 2
	ClusterStatus_CLUSTER_STATUS_NO_QUORUM   ClusterStatus = 3
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_HEALTHY",
		1: "CLUSTER_STATUS_DEGRADED",
		2: "CLUSTER_STATUS_SPLIT_BRAIN",
		3: "CLUSTER_STATUS_NO_QUORUM",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_HEALTHY":     0,
		"CLUSTER_STATUS_DEGRADED":    1,
		"CLUSTER_STATUS_SPLIT_BRAIN": 2,
		"CLUSTER_STATUS_NO_QUORUM":   3,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_health_proto_enumTypes[1].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_reckon_health_proto_enumTypes[1]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{1}
}

type MemoryLevel int32

const (
	MemoryLevel_MEMORY_LEVEL_LOW      MemoryLevel = 0
	MemoryLevel_MEMORY_LEVEL_NORMAL   MemoryLevel = 1
	MemoryLevel_MEMORY_LEVEL_HIGH     MemoryLevel = 2
	MemoryLevel_MEMORY_LEVEL_CRITICAL MemoryLevel = 3
)

// Enum value maps for MemoryLevel.
var (
	MemoryLevel_name = map[int32]string{
		0: "MEMORY_LEVEL_LOW",
		1: "MEMORY_LEVEL_NORMAL",
		2: "MEMORY_LEVEL_HIGH",
		3: "MEMORY_LEVEL_CRITICAL",
	}
	MemoryLevel_value = map[string]int32{
		"MEMORY_LEVEL_LOW":      0,
		"MEMORY_LEVEL_NORMAL":   1,
		"MEMORY_LEVEL_HIGH":     2,
		"MEMORY_LEVEL_CRITICAL": 3,
	}
)

func (x MemoryLevel) Enum() *MemoryLevel {
	p := new(MemoryLevel)
	*p = x
	return p
}

func (x MemoryLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_health_proto_enumTypes[2].Descriptor()
}

func (MemoryLevel) Type() protoreflect.EnumType {
	return &file_reckon_health_proto_enumTypes[2]
}

func (x MemoryLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryLevel.Descriptor instead.
func (MemoryLevel) EnumDescriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{2}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_reckon_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_reckon_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{1}
}

type ClusterCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCheckRequest) Reset() {
	*x = ClusterCheckRequest{}
	mi := &file_reckon_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCheckRequest) ProtoMessage() {}

func (x *ClusterCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCheckRequest.ProtoReflect.Descriptor instead.
func (*ClusterCheckRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterCheckRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type MemoryLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryLevelRequest) Reset() {
	*x = MemoryLevelRequest{}
	mi := &file_reckon_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryLevelRequest) ProtoMessage() {}

func (x *MemoryLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryLevelRequest.ProtoReflect.Descriptor instead.
func (*MemoryLevelRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryLevelRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type MemoryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStatsRequest) Reset() {
	*x = MemoryStatsRequest{}
	mi := &file_reckon_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatsRequest) ProtoMessage() {}

func (x *MemoryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatsRequest.ProtoReflect.Descriptor instead.
func (*MemoryStatsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryStatsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=reckon.gateway.v1.HealthStatus" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_reckon_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_HEALTHY
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=reckon.gateway.v1.HealthStatus" json:"status,omitempty"`
	Stores        map[string]uint32      `protobuf:"bytes,2,rep,name=stores,proto3" json:"stores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TotalWorkers  uint32                 `protobuf:"varint,3,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	Node          string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_reckon_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_HEALTHY
}

func (x *HealthResponse) GetStores() map[string]uint32 {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *HealthResponse) GetTotalWorkers() uint32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *HealthResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ClusterCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClusterStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=reckon.gateway.v1.ClusterStatus" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCheckResponse) Reset() {
	*x = ClusterCheckResponse{}
	mi := &file_reckon_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCheckResponse) ProtoMessage() {}

func (x *ClusterCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCheckResponse.ProtoReflect.Descriptor instead.
func (*ClusterCheckResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterCheckResponse) GetStatus() ClusterStatus {
	if x != nil {
		return x.Status
	}
	return ClusterStatus_CLUSTER_STATUS_HEALTHY
}

func (x *ClusterCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type MemoryLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         MemoryLevel            `protobuf:"varint,1,opt,name=level,proto3,enum=reckon.gateway.v1.MemoryLevel" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryLevelResponse) Reset() {
	*x = MemoryLevelResponse{}
	mi := &file_reckon_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryLevelResponse) ProtoMessage() {}

func (x *MemoryLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryLevelResponse.ProtoReflect.Descriptor instead.
func (*MemoryLevelResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryLevelResponse) GetLevel() MemoryLevel {
	if x != nil {
		return x.Level
	}
	return MemoryLevel_MEMORY_LEVEL_LOW
}

type MemoryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     uint64                 `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,3,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	Breakdown     map[string]uint64      `protobuf:"bytes,4,rep,name=breakdown,proto3" json:"breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStatsResponse) Reset() {
	*x = MemoryStatsResponse{}
	mi := &file_reckon_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatsResponse) ProtoMessage() {}

func (x *MemoryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatsResponse.ProtoReflect.Descriptor instead.
func (*MemoryStatsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{9}
}

func (x *MemoryStatsResponse) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MemoryStatsResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MemoryStatsResponse) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *MemoryStatsResponse) GetBreakdown() map[string]uint64 {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type GetServerInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Store to inquire about. Required - integrity configuration is
	// per-store, not gateway-global.
	StoreId       string `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_reckon_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{10}
}

func (x *GetServerInfoRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type ServerInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Versions of the underlying packages, advertised so clients can
	// negotiate features and surface compatibility errors locally
	// rather than discovering them via failed RPCs.
	ReckonDbVersion      string `protobuf:"bytes,1,opt,name=reckon_db_version,json=reckonDbVersion,proto3" json:"reckon_db_version,omitempty"`
	ReckonGatewayVersion string `protobuf:"bytes,2,opt,name=reckon_gateway_version,json=reckonGatewayVersion,proto3" json:"reckon_gateway_version,omitempty"`
	// Tamper-resistance algorithm identifier for chain hashes on
	// RecordedEvent.prev_event_hash and SnapshotRecord.anchor_hash.
	//
	// Current value: "sha256-deterministic-etf-v1"
	//   - sha256: hash function
	//   - deterministic-etf: canonical encoding via Erlang's
	//     term_to_binary with the deterministic flag (ETF v2)
	//   - v1: format version; bumped if the canonical encoding ever
	//     changes
	//
	// Polyglot clients use this string to confirm they have a
	// compatible chain-hash verifier before they begin walking
	// received events. Empty string when integrity is disabled on
	// the store.
	IntegrityAlgo string `protobuf:"bytes,3,opt,name=integrity_algo,json=integrityAlgo,proto3" json:"integrity_algo,omitempty"`
	// Whether the addressed store has integrity enabled. When false,
	// RecordedEvent.prev_event_hash and SnapshotRecord.anchor_hash
	// will be empty bytes on all events from this store regardless
	// of age.
	IntegrityEnabled bool `protobuf:"varint,4,opt,name=integrity_enabled,json=integrityEnabled,proto3" json:"integrity_enabled,omitempty"`
	// Current writer HMAC key ID for the addressed store. Always 1
	// in 0.2.0 / reckon-db 2.1.0; reserved for key rotation in
	// reckon-db 2.2. Zero when integrity_enabled is false. The key
	// itself is NEVER returned over the wire.
	HmacKeyId uint32 `protobuf:"varint,5,opt,name=hmac_key_id,json=hmacKeyId,proto3" json:"hmac_key_id,omitempty"`
	// Server-advertised API compatibility version. Clients can use
	// this to detect breaking proto changes when the proto file is
	// not in sync.
	ApiCompatibilityVersion string `protobuf:"bytes,6,opt,name=api_compatibility_version,json=apiCompatibilityVersion,proto3" json:"api_compatibility_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_reckon_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_reckon_health_proto_rawDescGZIP(), []int{11}
}

func (x *ServerInfoResponse) GetReckonDbVersion() string {
	if x != nil {
		return x.ReckonDbVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetReckonGatewayVersion() string {
	if x != nil {
		return x.ReckonGatewayVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetIntegrityAlgo() string {
	if x != nil {
		return x.IntegrityAlgo
	}
	return ""
}

func (x *ServerInfoResponse) GetIntegrityEnabled() bool {
	if x != nil {
		return x.IntegrityEnabled
	}
	return false
}

func (x *ServerInfoResponse) GetHmacKeyId() uint32 {
	if x != nil {
		return x.HmacKeyId
	}
	return 0
}

func (x *ServerInfoResponse) GetApiCompatibilityVersion() string {
	if x != nil {
		return x.ApiCompatibilityVersion
	}
	return ""
}

var File_reckon_health_proto protoreflect.FileDescriptor

const file_reckon_health_proto_rawDesc = "" +
	"\n" +
	"\x13reckon_health.proto\x12\x11reckon.gateway.v1\"/\n" +
	"\x12HealthCheckRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\x0f\n" +
	"\rHealthRequest\"0\n" +
	"\x13ClusterCheckRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"/\n" +
	"\x12MemoryLevelRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"/\n" +
	"\x12MemoryStatsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\xd9\x01\n" +
	"\x13HealthCheckResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.reckon.gateway.v1.HealthStatusR\x06status\x12M\n" +
	"\adetails\x18\x02 \x03(\v23.reckon.gateway.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\x0eHealthResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.reckon.gateway.v1.HealthStatusR\x06status\x12E\n" +
	"\x06stores\x18\x02 \x03(\v2-.reckon.gateway.v1.HealthResponse.StoresEntryR\x06stores\x12#\n" +
	"\rtotal_workers\x18\x03 \x01(\rR\ftotalWorkers\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a9\n" +
	"\vStoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x14ClusterCheckResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .reckon.gateway.v1.ClusterStatusR\x06status\x12N\n" +
	"\adetails\x18\x02 \x03(\v24.reckon.gateway.v1.ClusterCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x13MemoryLevelResponse\x124\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1e.reckon.gateway.v1.MemoryLevelR\x05level\"\x8d\x02\n" +
	"\x13MemoryStatsResponse\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12#\n" +
	"\rusage_percent\x18\x03 \x01(\x01R\fusagePercent\x12S\n" +
	"\tbreakdown\x18\x04 \x03(\v25.reckon.gateway.v1.MemoryStatsResponse.BreakdownEntryR\tbreakdown\x1a<\n" +
	"\x0eBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"1\n" +
	"\x14GetServerInfoRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\xa6\x02\n" +
	"\x12ServerInfoResponse\x12*\n" +
	"\x11reckon_db_version\x18\x01 \x01(\tR\x0freckonDbVersion\x124\n" +
	"\x16reckon_gateway_version\x18\x02 \x01(\tR\x14reckonGatewayVersion\x12%\n" +
	"\x0eintegrity_algo\x18\x03 \x01(\tR\rintegrityAlgo\x12+\n" +
	"\x11integrity_enabled\x18\x04 \x01(\bR\x10integrityEnabled\x12\x1e\n" +
	"\vhmac_key_id\x18\x05 \x01(\rR\thmacKeyId\x12:\n" +
	"\x19api_compatibility_version\x18\x06 \x01(\tR\x17apiCompatibilityVersion*b\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x00\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02*\x86\x01\n" +
	"\rClusterStatus\x12\x1a\n" +
	"\x16CLUSTER_STATUS_HEALTHY\x10\x00\x12\x1b\n" +
	"\x17CLUSTER_STATUS_DEGRADED\x10\x01\x12\x1e\n" +
	"\x1aCLUSTER_STATUS_SPLIT_BRAIN\x10\x02\x12\x1c\n" +
	"\x18CLUSTER_STATUS_NO_QUORUM\x10\x03*n\n" +
	"\vMemoryLevel\x12\x14\n" +
	"\x10MEMORY_LEVEL_LOW\x10\x00\x12\x17\n" +
	"\x13MEMORY_LEVEL_NORMAL\x10\x01\x12\x15\n" +
	"\x11MEMORY_LEVEL_HIGH\x10\x02\x12\x19\n" +
	"\x15MEMORY_LEVEL_CRITICAL\x10\x032\xa0\x06\n" +
	"\rHealthService\x12V\n" +
	"\x05Check\x12%.reckon.gateway.v1.HealthCheckRequest\x1a&.reckon.gateway.v1.HealthCheckResponse\x12M\n" +
	"\x06Health\x12 .reckon.gateway.v1.HealthRequest\x1a!.reckon.gateway.v1.HealthResponse\x12k\n" +
	"\x18VerifyClusterConsistency\x12&.reckon.gateway.v1.ClusterCheckRequest\x1a'.reckon.gateway.v1.ClusterCheckResponse\x12l\n" +
	"\x19VerifyMembershipConsensus\x12&.reckon.gateway.v1.ClusterCheckRequest\x1a'.reckon.gateway.v1.ClusterCheckResponse\x12j\n" +
	"\x17CheckRaftLogConsistency\x12&.reckon.gateway.v1.ClusterCheckRequest\x1a'.reckon.gateway.v1.ClusterCheckResponse\x12_\n" +
	"\x0eGetMemoryLevel\x12%.reckon.gateway.v1.MemoryLevelRequest\x1a&.reckon.gateway.v1.MemoryLevelResponse\x12_\n" +
	"\x0eGetMemoryStats\x12%.reckon.gateway.v1.MemoryStatsRequest\x1a&.reckon.gateway.v1.MemoryStatsResponse\x12_\n" +
	"\rGetServerInfo\x12'.reckon.gateway.v1.GetServerInfoRequest\x1a%.reckon.gateway.v1.ServerInfoResponseBAZ?github.com/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_health_proto_rawDescOnce sync.Once
	file_reckon_health_proto_rawDescData []byte
)

func file_reckon_health_proto_rawDescGZIP() []byte {
	file_reckon_health_proto_rawDescOnce.Do(func() {
		file_reckon_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_health_proto_rawDesc), len(file_reckon_health_proto_rawDesc)))
	})
	return file_reckon_health_proto_rawDescData
}

var file_reckon_health_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_reckon_health_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_reckon_health_proto_goTypes = []any{
	(HealthStatus)(0),            // 0: reckon.gateway.v1.HealthStatus
	(ClusterStatus)(0),           // 1: reckon.gateway.v1.ClusterStatus
	(MemoryLevel)(0),             // 2: reckon.gateway.v1.MemoryLevel
	(*HealthCheckRequest)(nil),   // 3: reckon.gateway.v1.HealthCheckRequest
	(*HealthRequest)(nil),        // 4: reckon.gateway.v1.HealthRequest
	(*ClusterCheckRequest)(nil),  // 5: reckon.gateway.v1.ClusterCheckRequest
	(*MemoryLevelRequest)(nil),   // 6: reckon.gateway.v1.MemoryLevelRequest
	(*MemoryStatsRequest)(nil),   // 7: reckon.gateway.v1.MemoryStatsRequest
	(*HealthCheckResponse)(nil),  // 8: reckon.gateway.v1.HealthCheckResponse
	(*HealthResponse)(nil),       // 9: reckon.gateway.v1.HealthResponse
	(*ClusterCheckResponse)(nil), // 10: reckon.gateway.v1.ClusterCheckResponse
	(*MemoryLevelResponse)(nil),  // 11: reckon.gateway.v1.MemoryLevelResponse
	(*MemoryStatsResponse)(nil),  // 12: reckon.gateway.v1.MemoryStatsResponse
	(*GetServerInfoRequest)(nil), // 13: reckon.gateway.v1.GetServerInfoRequest
	(*ServerInfoResponse)(nil),   // 14: reckon.gateway.v1.ServerInfoResponse
	nil,                          // 15: reckon.gateway.v1.HealthCheckResponse.DetailsEntry
	nil,                          // 16: reckon.gateway.v1.HealthResponse.StoresEntry
	nil,                          // 17: reckon.gateway.v1.ClusterCheckResponse.DetailsEntry
	nil,                          // 18: reckon.gateway.v1.MemoryStatsResponse.BreakdownEntry
}
var file_reckon_health_proto_depIdxs = []int32{
	0,  // 0: reckon.gateway.v1.HealthCheckResponse.status:type_name -> reckon.gateway.v1.HealthStatus
	15, // 1: reckon.gateway.v1.HealthCheckResponse.details:type_name -> reckon.gateway.v1.HealthCheckResponse.DetailsEntry
	0,  // 2: reckon.gateway.v1.HealthResponse.status:type_name -> reckon.gateway.v1.HealthStatus
	16, // 3: reckon.gateway.v1.HealthResponse.stores:type_name -> reckon.gateway.v1.HealthResponse.StoresEntry
	1,  // 4: reckon.gateway.v1.ClusterCheckResponse.status:type_name -> reckon.gateway.v1.ClusterStatus
	17, // 5: reckon.gateway.v1.ClusterCheckResponse.details:type_name -> reckon.gateway.v1.ClusterCheckResponse.DetailsEntry
	2,  // 6: reckon.gateway.v1.MemoryLevelResponse.level:type_name -> reckon.gateway.v1.MemoryLevel
	18, // 7: reckon.gateway.v1.MemoryStatsResponse.breakdown:type_name -> reckon.gateway.v1.MemoryStatsResponse.BreakdownEntry
	3,  // 8: reckon.gateway.v1.HealthService.Check:input_type -> reckon.gateway.v1.HealthCheckRequest
	4,  // 9: reckon.gateway.v1.HealthService.Health:input_type -> reckon.gateway.v1.HealthRequest
	5,  // 10: reckon.gateway.v1.HealthService.VerifyClusterConsistency:input_type -> reckon.gateway.v1.ClusterCheckRequest
	5,  // 11: reckon.gateway.v1.HealthService.VerifyMembershipConsensus:input_type -> reckon.gateway.v1.ClusterCheckRequest
	5,  // 12: reckon.gateway.v1.HealthService.CheckRaftLogConsistency:input_type -> reckon.gateway.v1.ClusterCheckRequest
	6,  // 13: reckon.gateway.v1.HealthService.GetMemoryLevel:input_type -> reckon.gateway.v1.MemoryLevelRequest
	7,  // 14: reckon.gateway.v1.HealthService.GetMemoryStats:input_type -> reckon.gateway.v1.MemoryStatsRequest
	13, // 15: reckon.gateway.v1.HealthService.GetServerInfo:input_type -> reckon.gateway.v1.GetServerInfoRequest
	8,  // 16: reckon.gateway.v1.HealthService.Check:output_type -> reckon.gateway.v1.HealthCheckResponse
	9,  // 17: reckon.gateway.v1.HealthService.Health:output_type -> reckon.gateway.v1.HealthResponse
	10, // 18: reckon.gateway.v1.HealthService.VerifyClusterConsistency:output_type -> reckon.gateway.v1.ClusterCheckResponse
	10, // 19: reckon.gateway.v1.HealthService.VerifyMembershipConsensus:output_type -> reckon.gateway.v1.ClusterCheckResponse
	10, // 20: reckon.gateway.v1.HealthService.CheckRaftLogConsistency:output_type -> reckon.gateway.v1.ClusterCheckResponse
	11, // 21: reckon.gateway.v1.HealthService.GetMemoryLevel:output_type -> reckon.gateway.v1.MemoryLevelResponse
	12, // 22: reckon.gateway.v1.HealthService.GetMemoryStats:output_type -> reckon.gateway.v1.MemoryStatsResponse
	14, // 23: reckon.gateway.v1.HealthService.GetServerInfo:output_type -> reckon.gateway.v1.ServerInfoResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_reckon_health_proto_init() }
func file_reckon_health_proto_init() {
	if File_reckon_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_health_proto_rawDesc), len(file_reckon_health_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_health_proto_goTypes,
		DependencyIndexes: file_reckon_health_proto_depIdxs,
		EnumInfos:         file_reckon_health_proto_enumTypes,
		MessageInfos:      file_reckon_health_proto_msgTypes,
	}.Build()
	File_reckon_health_proto = out.File
	file_reckon_health_proto_goTypes = nil
	file_reckon_health_proto_depIdxs = nil
}
