// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reckon_admin.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreStatsRequest) Reset() {
	*x = StoreStatsRequest{}
	mi := &file_reckon_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStatsRequest) ProtoMessage() {}

func (x *StoreStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStatsRequest.ProtoReflect.Descriptor instead.
func (*StoreStatsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{0}
}

func (x *StoreStatsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type StoreStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalStreams       uint64                 `protobuf:"varint,1,opt,name=total_streams,json=totalStreams,proto3" json:"total_streams,omitempty"`
	TotalEvents        uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	TotalSubscriptions uint64                 `protobuf:"varint,3,opt,name=total_subscriptions,json=totalSubscriptions,proto3" json:"total_subscriptions,omitempty"`
	TotalSnapshots     uint64                 `protobuf:"varint,4,opt,name=total_snapshots,json=totalSnapshots,proto3" json:"total_snapshots,omitempty"`
	Details            map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StoreStatsResponse) Reset() {
	*x = StoreStatsResponse{}
	mi := &file_reckon_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreStatsResponse) ProtoMessage() {}

func (x *StoreStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreStatsResponse.ProtoReflect.Descriptor instead.
func (*StoreStatsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StoreStatsResponse) GetTotalStreams() uint64 {
	if x != nil {
		return x.TotalStreams
	}
	return 0
}

func (x *StoreStatsResponse) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *StoreStatsResponse) GetTotalSubscriptions() uint64 {
	if x != nil {
		return x.TotalSubscriptions
	}
	return 0
}

func (x *StoreStatsResponse) GetTotalSnapshots() uint64 {
	if x != nil {
		return x.TotalSnapshots
	}
	return 0
}

func (x *StoreStatsResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type StreamInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoRequest) Reset() {
	*x = StreamInfoRequest{}
	mi := &file_reckon_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoRequest) ProtoMessage() {}

func (x *StreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoRequest.ProtoReflect.Descriptor instead.
func (*StreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{2}
}

func (x *StreamInfoRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StreamInfoRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type StreamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	EventCount    uint64                 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastEventAt   int64                  `protobuf:"varint,5,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	EventTypes    []string               `protobuf:"bytes,6,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfoResponse) Reset() {
	*x = StreamInfoResponse{}
	mi := &file_reckon_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoResponse) ProtoMessage() {}

func (x *StreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoResponse.ProtoReflect.Descriptor instead.
func (*StreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{3}
}

func (x *StreamInfoResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamInfoResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StreamInfoResponse) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StreamInfoResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StreamInfoResponse) GetLastEventAt() int64 {
	if x != nil {
		return x.LastEventAt
	}
	return 0
}

func (x *StreamInfoResponse) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EventTypeSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeSummaryRequest) Reset() {
	*x = EventTypeSummaryRequest{}
	mi := &file_reckon_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeSummaryRequest) ProtoMessage() {}

func (x *EventTypeSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeSummaryRequest.ProtoReflect.Descriptor instead.
func (*EventTypeSummaryRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{4}
}

func (x *EventTypeSummaryRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type EventTypeSummaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeSummaryEntry) Reset() {
	*x = EventTypeSummaryEntry{}
	mi := &file_reckon_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeSummaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeSummaryEntry) ProtoMessage() {}

func (x *EventTypeSummaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeSummaryEntry.ProtoReflect.Descriptor instead.
func (*EventTypeSummaryEntry) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{5}
}

func (x *EventTypeSummaryEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventTypeSummaryEntry) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EventTypeSummaryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Entries       []*EventTypeSummaryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeSummaryResponse) Reset() {
	*x = EventTypeSummaryResponse{}
	mi := &file_reckon_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeSummaryResponse) ProtoMessage() {}

func (x *EventTypeSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeSummaryResponse.ProtoReflect.Descriptor instead.
func (*EventTypeSummaryResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{6}
}

func (x *EventTypeSummaryResponse) GetEntries() []*EventTypeSummaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScavengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScavengeRequest) Reset() {
	*x = ScavengeRequest{}
	mi := &file_reckon_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScavengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScavengeRequest) ProtoMessage() {}

func (x *ScavengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScavengeRequest.ProtoReflect.Descriptor instead.
func (*ScavengeRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ScavengeRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ScavengeRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ScavengeRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScavengeResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventsRemoved       uint64                 `protobuf:"varint,1,opt,name=events_removed,json=eventsRemoved,proto3" json:"events_removed,omitempty"`
	EventsRemaining     uint64                 `protobuf:"varint,2,opt,name=events_remaining,json=eventsRemaining,proto3" json:"events_remaining,omitempty"`
	SpaceReclaimedBytes uint64                 `protobuf:"varint,3,opt,name=space_reclaimed_bytes,json=spaceReclaimedBytes,proto3" json:"space_reclaimed_bytes,omitempty"`
	Details             map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ScavengeResponse) Reset() {
	*x = ScavengeResponse{}
	mi := &file_reckon_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScavengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScavengeResponse) ProtoMessage() {}

func (x *ScavengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScavengeResponse.ProtoReflect.Descriptor instead.
func (*ScavengeResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ScavengeResponse) GetEventsRemoved() uint64 {
	if x != nil {
		return x.EventsRemoved
	}
	return 0
}

func (x *ScavengeResponse) GetEventsRemaining() uint64 {
	if x != nil {
		return x.EventsRemaining
	}
	return 0
}

func (x *ScavengeResponse) GetSpaceReclaimedBytes() uint64 {
	if x != nil {
		return x.SpaceReclaimedBytes
	}
	return 0
}

func (x *ScavengeResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ScavengeMatchingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Options       map[string]string      `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScavengeMatchingRequest) Reset() {
	*x = ScavengeMatchingRequest{}
	mi := &file_reckon_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScavengeMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScavengeMatchingRequest) ProtoMessage() {}

func (x *ScavengeMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScavengeMatchingRequest.ProtoReflect.Descriptor instead.
func (*ScavengeMatchingRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ScavengeMatchingRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ScavengeMatchingRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ScavengeMatchingRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ScavengeMatchingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScavengeResponse    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScavengeMatchingResponse) Reset() {
	*x = ScavengeMatchingResponse{}
	mi := &file_reckon_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScavengeMatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScavengeMatchingResponse) ProtoMessage() {}

func (x *ScavengeMatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScavengeMatchingResponse.ProtoReflect.Descriptor instead.
func (*ScavengeMatchingResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ScavengeMatchingResponse) GetResults() []*ScavengeResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Options       map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_reckon_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{11}
}

func (x *CreateLinkRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CreateLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLinkRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateLinkRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateLinkRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_reckon_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{12}
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_reckon_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteLinkRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DeleteLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_reckon_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{14}
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_reckon_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetLinkRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LinkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkInfo) Reset() {
	*x = LinkInfo{}
	mi := &file_reckon_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkInfo) ProtoMessage() {}

func (x *LinkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkInfo.ProtoReflect.Descriptor instead.
func (*LinkInfo) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{16}
}

func (x *LinkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LinkInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LinkInfo) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type StartLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLinkRequest) Reset() {
	*x = StartLinkRequest{}
	mi := &file_reckon_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLinkRequest) ProtoMessage() {}

func (x *StartLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLinkRequest.ProtoReflect.Descriptor instead.
func (*StartLinkRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{17}
}

func (x *StartLinkRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StartLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartLinkResponse) Reset() {
	*x = StartLinkResponse{}
	mi := &file_reckon_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLinkResponse) ProtoMessage() {}

func (x *StartLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLinkResponse.ProtoReflect.Descriptor instead.
func (*StartLinkResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{18}
}

type StopLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLinkRequest) Reset() {
	*x = StopLinkRequest{}
	mi := &file_reckon_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLinkRequest) ProtoMessage() {}

func (x *StopLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLinkRequest.ProtoReflect.Descriptor instead.
func (*StopLinkRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{19}
}

func (x *StopLinkRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StopLinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopLinkResponse) Reset() {
	*x = StopLinkResponse{}
	mi := &file_reckon_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopLinkResponse) ProtoMessage() {}

func (x *StopLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopLinkResponse.ProtoReflect.Descriptor instead.
func (*StopLinkResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{20}
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_reckon_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListLinksRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkInfo            `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_reckon_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ListLinksResponse) GetLinks() []*LinkInfo {
	if x != nil {
		return x.Links
	}
	return nil
}

type LinkRuntimeInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EventsProcessed uint64                 `protobuf:"varint,3,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	Details         map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LinkRuntimeInfo) Reset() {
	*x = LinkRuntimeInfo{}
	mi := &file_reckon_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRuntimeInfo) ProtoMessage() {}

func (x *LinkRuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRuntimeInfo.ProtoReflect.Descriptor instead.
func (*LinkRuntimeInfo) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{23}
}

func (x *LinkRuntimeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkRuntimeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LinkRuntimeInfo) GetEventsProcessed() uint64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *LinkRuntimeInfo) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ReloadCatalogueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCatalogueRequest) Reset() {
	*x = ReloadCatalogueRequest{}
	mi := &file_reckon_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCatalogueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCatalogueRequest) ProtoMessage() {}

func (x *ReloadCatalogueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCatalogueRequest.ProtoReflect.Descriptor instead.
func (*ReloadCatalogueRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{24}
}

type ReloadCatalogueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_ids newly connected since the previous catalogue state.
	Added []string `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	// cluster_ids retired (removed from clusters.eterm).
	Removed []string `protobuf:"bytes,2,rep,name=removed,proto3" json:"removed,omitempty"`
	// cluster_ids whose config (members or cookie) changed and whose
	// connector was therefore terminated + restarted.
	Restarted []string `protobuf:"bytes,3,rep,name=restarted,proto3" json:"restarted,omitempty"`
	// Populated only on configuration-load failure (malformed eterm,
	// duplicate cluster_id, missing required field). When non-empty,
	// the live state was NOT mutated.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadCatalogueResponse) Reset() {
	*x = ReloadCatalogueResponse{}
	mi := &file_reckon_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadCatalogueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCatalogueResponse) ProtoMessage() {}

func (x *ReloadCatalogueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCatalogueResponse.ProtoReflect.Descriptor instead.
func (*ReloadCatalogueResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ReloadCatalogueResponse) GetAdded() []string {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *ReloadCatalogueResponse) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *ReloadCatalogueResponse) GetRestarted() []string {
	if x != nil {
		return x.Restarted
	}
	return nil
}

func (x *ReloadCatalogueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCatalogueStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogueStatusRequest) Reset() {
	*x = GetCatalogueStatusRequest{}
	mi := &file_reckon_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogueStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogueStatusRequest) ProtoMessage() {}

func (x *GetCatalogueStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogueStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogueStatusRequest) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{26}
}

type GetCatalogueStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total distinct store_ids visible across every connected cluster.
	CatalogueSize int32 `protobuf:"varint,1,opt,name=catalogue_size,json=catalogueSize,proto3" json:"catalogue_size,omitempty"`
	// Process uptime in milliseconds (informational; ops dashboards).
	GatewayUptimeMs int64 `protobuf:"varint,2,opt,name=gateway_uptime_ms,json=gatewayUptimeMs,proto3" json:"gateway_uptime_ms,omitempty"`
	// Per-cluster connector status.
	Clusters      []*CatalogueClusterStatus `protobuf:"bytes,3,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogueStatusResponse) Reset() {
	*x = GetCatalogueStatusResponse{}
	mi := &file_reckon_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogueStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogueStatusResponse) ProtoMessage() {}

func (x *GetCatalogueStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogueStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogueStatusResponse) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{27}
}

func (x *GetCatalogueStatusResponse) GetCatalogueSize() int32 {
	if x != nil {
		return x.CatalogueSize
	}
	return 0
}

func (x *GetCatalogueStatusResponse) GetGatewayUptimeMs() int64 {
	if x != nil {
		return x.GatewayUptimeMs
	}
	return 0
}

func (x *GetCatalogueStatusResponse) GetClusters() []*CatalogueClusterStatus {
	if x != nil {
		return x.Clusters
	}
	return nil
}

// Status of a single cluster connector inside the catalogue. Distinct
// from `ClusterStatus` (enum) in reckon_health.proto, which describes
// raft-quorum verification outcomes; collapsing both onto the same
// symbol would collide in the `reckon.gateway.v1` namespace and
// break code generators that enforce single-definition (buf/protoc).
type CatalogueClusterStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-assigned label from clusters.eterm.
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Currently-connected Erlang dist members of the cluster.
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	// Distinct store_ids the gateway sees from this cluster.
	StoreCount int32 `protobuf:"varint,3,opt,name=store_count,json=storeCount,proto3" json:"store_count,omitempty"`
	// "up" | "degraded" | "unreachable" | "not_yet_connected".
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// ISO-8601 timestamp of the last successful refresh tick.
	// Empty string when the connector has never reached the cluster.
	LastRefresh string `protobuf:"bytes,5,opt,name=last_refresh,json=lastRefresh,proto3" json:"last_refresh,omitempty"`
	// Free-form recent error description. Empty when status = "up".
	// NEVER contains the cookie value.
	LastError     string `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogueClusterStatus) Reset() {
	*x = CatalogueClusterStatus{}
	mi := &file_reckon_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogueClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogueClusterStatus) ProtoMessage() {}

func (x *CatalogueClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogueClusterStatus.ProtoReflect.Descriptor instead.
func (*CatalogueClusterStatus) Descriptor() ([]byte, []int) {
	return file_reckon_admin_proto_rawDescGZIP(), []int{28}
}

func (x *CatalogueClusterStatus) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *CatalogueClusterStatus) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *CatalogueClusterStatus) GetStoreCount() int32 {
	if x != nil {
		return x.StoreCount
	}
	return 0
}

func (x *CatalogueClusterStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CatalogueClusterStatus) GetLastRefresh() string {
	if x != nil {
		return x.LastRefresh
	}
	return ""
}

func (x *CatalogueClusterStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_reckon_admin_proto protoreflect.FileDescriptor

const file_reckon_admin_proto_rawDesc = "" +
	"\n" +
	"\x12reckon_admin.proto\x12\x11reckon.gateway.v1\".\n" +
	"\x11StoreStatsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\xc0\x02\n" +
	"\x12StoreStatsResponse\x12#\n" +
	"\rtotal_streams\x18\x01 \x01(\x04R\ftotalStreams\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\x12/\n" +
	"\x13total_subscriptions\x18\x03 \x01(\x04R\x12totalSubscriptions\x12'\n" +
	"\x0ftotal_snapshots\x18\x04 \x01(\x04R\x0etotalSnapshots\x12L\n" +
	"\adetails\x18\x05 \x03(\v22.reckon.gateway.v1.StoreStatsResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x11StreamInfoRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"\xd0\x01\n" +
	"\x12StreamInfoResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x04R\n" +
	"eventCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\"\n" +
	"\rlast_event_at\x18\x05 \x01(\x03R\vlastEventAt\x12\x1f\n" +
	"\vevent_types\x18\x06 \x03(\tR\n" +
	"eventTypes\"4\n" +
	"\x17EventTypeSummaryRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"L\n" +
	"\x15EventTypeSummaryEntry\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"^\n" +
	"\x18EventTypeSummaryResponse\x12B\n" +
	"\aentries\x18\x01 \x03(\v2(.reckon.gateway.v1.EventTypeSummaryEntryR\aentries\"\xd0\x01\n" +
	"\x0fScavengeRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12I\n" +
	"\aoptions\x18\x03 \x03(\v2/.reckon.gateway.v1.ScavengeRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\x10ScavengeResponse\x12%\n" +
	"\x0eevents_removed\x18\x01 \x01(\x04R\reventsRemoved\x12)\n" +
	"\x10events_remaining\x18\x02 \x01(\x04R\x0feventsRemaining\x122\n" +
	"\x15space_reclaimed_bytes\x18\x03 \x01(\x04R\x13spaceReclaimedBytes\x12J\n" +
	"\adetails\x18\x04 \x03(\v20.reckon.gateway.v1.ScavengeResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x17ScavengeMatchingRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12Q\n" +
	"\aoptions\x18\x03 \x03(\v27.reckon.gateway.v1.ScavengeMatchingRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x18ScavengeMatchingResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.reckon.gateway.v1.ScavengeResponseR\aresults\"\xfb\x01\n" +
	"\x11CreateLinkRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12K\n" +
	"\aoptions\x18\x05 \x03(\v21.reckon.gateway.v1.CreateLinkRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12CreateLinkResponse\"B\n" +
	"\x11DeleteLinkRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteLinkResponse\"?\n" +
	"\x0eGetLinkRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xce\x01\n" +
	"\bLinkInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12B\n" +
	"\aoptions\x18\x04 \x03(\v2(.reckon.gateway.v1.LinkInfo.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x10StartLinkRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x13\n" +
	"\x11StartLinkResponse\"@\n" +
	"\x0fStopLinkRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x12\n" +
	"\x10StopLinkResponse\"-\n" +
	"\x10ListLinksRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"F\n" +
	"\x11ListLinksResponse\x121\n" +
	"\x05links\x18\x01 \x03(\v2\x1b.reckon.gateway.v1.LinkInfoR\x05links\"\xef\x01\n" +
	"\x0fLinkRuntimeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10events_processed\x18\x03 \x01(\x04R\x0feventsProcessed\x12I\n" +
	"\adetails\x18\x04 \x03(\v2/.reckon.gateway.v1.LinkRuntimeInfo.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16ReloadCatalogueRequest\"}\n" +
	"\x17ReloadCatalogueResponse\x12\x14\n" +
	"\x05added\x18\x01 \x03(\tR\x05added\x12\x18\n" +
	"\aremoved\x18\x02 \x03(\tR\aremoved\x12\x1c\n" +
	"\trestarted\x18\x03 \x03(\tR\trestarted\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x1b\n" +
	"\x19GetCatalogueStatusRequest\"\xb6\x01\n" +
	"\x1aGetCatalogueStatusResponse\x12%\n" +
	"\x0ecatalogue_size\x18\x01 \x01(\x05R\rcatalogueSize\x12*\n" +
	"\x11gateway_uptime_ms\x18\x02 \x01(\x03R\x0fgatewayUptimeMs\x12E\n" +
	"\bclusters\x18\x03 \x03(\v2).reckon.gateway.v1.CatalogueClusterStatusR\bclusters\"\xcc\x01\n" +
	"\x16CatalogueClusterStatus\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\x12\x1f\n" +
	"\vstore_count\x18\x03 \x01(\x05R\n" +
	"storeCount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\flast_refresh\x18\x05 \x01(\tR\vlastRefresh\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError2\x90\v\n" +
	"\fAdminService\x12\\\n" +
	"\rGetStoreStats\x12$.reckon.gateway.v1.StoreStatsRequest\x1a%.reckon.gateway.v1.StoreStatsResponse\x12\\\n" +
	"\rGetStreamInfo\x12$.reckon.gateway.v1.StreamInfoRequest\x1a%.reckon.gateway.v1.StreamInfoResponse\x12n\n" +
	"\x13GetEventTypeSummary\x12*.reckon.gateway.v1.EventTypeSummaryRequest\x1a+.reckon.gateway.v1.EventTypeSummaryResponse\x12S\n" +
	"\bScavenge\x12\".reckon.gateway.v1.ScavengeRequest\x1a#.reckon.gateway.v1.ScavengeResponse\x12k\n" +
	"\x10ScavengeMatching\x12*.reckon.gateway.v1.ScavengeMatchingRequest\x1a+.reckon.gateway.v1.ScavengeMatchingResponse\x12Y\n" +
	"\x0eScavengeDryRun\x12\".reckon.gateway.v1.ScavengeRequest\x1a#.reckon.gateway.v1.ScavengeResponse\x12Y\n" +
	"\n" +
	"CreateLink\x12$.reckon.gateway.v1.CreateLinkRequest\x1a%.reckon.gateway.v1.CreateLinkResponse\x12Y\n" +
	"\n" +
	"DeleteLink\x12$.reckon.gateway.v1.DeleteLinkRequest\x1a%.reckon.gateway.v1.DeleteLinkResponse\x12I\n" +
	"\aGetLink\x12!.reckon.gateway.v1.GetLinkRequest\x1a\x1b.reckon.gateway.v1.LinkInfo\x12V\n" +
	"\tListLinks\x12#.reckon.gateway.v1.ListLinksRequest\x1a$.reckon.gateway.v1.ListLinksResponse\x12V\n" +
	"\tStartLink\x12#.reckon.gateway.v1.StartLinkRequest\x1a$.reckon.gateway.v1.StartLinkResponse\x12S\n" +
	"\bStopLink\x12\".reckon.gateway.v1.StopLinkRequest\x1a#.reckon.gateway.v1.StopLinkResponse\x12T\n" +
	"\vGetLinkInfo\x12!.reckon.gateway.v1.GetLinkRequest\x1a\".reckon.gateway.v1.LinkRuntimeInfo\x12h\n" +
	"\x0fReloadCatalogue\x12).reckon.gateway.v1.ReloadCatalogueRequest\x1a*.reckon.gateway.v1.ReloadCatalogueResponse\x12q\n" +
	"\x12GetCatalogueStatus\x12,.reckon.gateway.v1.GetCatalogueStatusRequest\x1a-.reckon.gateway.v1.GetCatalogueStatusResponseBAZ?github.com/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_admin_proto_rawDescOnce sync.Once
	file_reckon_admin_proto_rawDescData []byte
)

func file_reckon_admin_proto_rawDescGZIP() []byte {
	file_reckon_admin_proto_rawDescOnce.Do(func() {
		file_reckon_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_admin_proto_rawDesc), len(file_reckon_admin_proto_rawDesc)))
	})
	return file_reckon_admin_proto_rawDescData
}

var file_reckon_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_reckon_admin_proto_goTypes = []any{
	(*StoreStatsRequest)(nil),          // 0: reckon.gateway.v1.StoreStatsRequest
	(*StoreStatsResponse)(nil),         // 1: reckon.gateway.v1.StoreStatsResponse
	(*StreamInfoRequest)(nil),          // 2: reckon.gateway.v1.StreamInfoRequest
	(*StreamInfoResponse)(nil),         // 3: reckon.gateway.v1.StreamInfoResponse
	(*EventTypeSummaryRequest)(nil),    // 4: reckon.gateway.v1.EventTypeSummaryRequest
	(*EventTypeSummaryEntry)(nil),      // 5: reckon.gateway.v1.EventTypeSummaryEntry
	(*EventTypeSummaryResponse)(nil),   // 6: reckon.gateway.v1.EventTypeSummaryResponse
	(*ScavengeRequest)(nil),            // 7: reckon.gateway.v1.ScavengeRequest
	(*ScavengeResponse)(nil),           // 8: reckon.gateway.v1.ScavengeResponse
	(*ScavengeMatchingRequest)(nil),    // 9: reckon.gateway.v1.ScavengeMatchingRequest
	(*ScavengeMatchingResponse)(nil),   // 10: reckon.gateway.v1.ScavengeMatchingResponse
	(*CreateLinkRequest)(nil),          // 11: reckon.gateway.v1.CreateLinkRequest
	(*CreateLinkResponse)(nil),         // 12: reckon.gateway.v1.CreateLinkResponse
	(*DeleteLinkRequest)(nil),          // 13: reckon.gateway.v1.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),         // 14: reckon.gateway.v1.DeleteLinkResponse
	(*GetLinkRequest)(nil),             // 15: reckon.gateway.v1.GetLinkRequest
	(*LinkInfo)(nil),                   // 16: reckon.gateway.v1.LinkInfo
	(*StartLinkRequest)(nil),           // 17: reckon.gateway.v1.StartLinkRequest
	(*StartLinkResponse)(nil),          // 18: reckon.gateway.v1.StartLinkResponse
	(*StopLinkRequest)(nil),            // 19: reckon.gateway.v1.StopLinkRequest
	(*StopLinkResponse)(nil),           // 20: reckon.gateway.v1.StopLinkResponse
	(*ListLinksRequest)(nil),           // 21: reckon.gateway.v1.ListLinksRequest
	(*ListLinksResponse)(nil),          // 22: reckon.gateway.v1.ListLinksResponse
	(*LinkRuntimeInfo)(nil),            // 23: reckon.gateway.v1.LinkRuntimeInfo
	(*ReloadCatalogueRequest)(nil),     // 24: reckon.gateway.v1.ReloadCatalogueRequest
	(*ReloadCatalogueResponse)(nil),    // 25: reckon.gateway.v1.ReloadCatalogueResponse
	(*GetCatalogueStatusRequest)(nil),  // 26: reckon.gateway.v1.GetCatalogueStatusRequest
	(*GetCatalogueStatusResponse)(nil), // 27: reckon.gateway.v1.GetCatalogueStatusResponse
	(*CatalogueClusterStatus)(nil),     // 28: reckon.gateway.v1.CatalogueClusterStatus
	nil,                                // 29: reckon.gateway.v1.StoreStatsResponse.DetailsEntry
	nil,                                // 30: reckon.gateway.v1.ScavengeRequest.OptionsEntry
	nil,                                // 31: reckon.gateway.v1.ScavengeResponse.DetailsEntry
	nil,                                // 32: reckon.gateway.v1.ScavengeMatchingRequest.OptionsEntry
	nil,                                // 33: reckon.gateway.v1.CreateLinkRequest.OptionsEntry
	nil,                                // 34: reckon.gateway.v1.LinkInfo.OptionsEntry
	nil,                                // 35: reckon.gateway.v1.LinkRuntimeInfo.DetailsEntry
}
var file_reckon_admin_proto_depIdxs = []int32{
	29, // 0: reckon.gateway.v1.StoreStatsResponse.details:type_name -> reckon.gateway.v1.StoreStatsResponse.DetailsEntry
	5,  // 1: reckon.gateway.v1.EventTypeSummaryResponse.entries:type_name -> reckon.gateway.v1.EventTypeSummaryEntry
	30, // 2: reckon.gateway.v1.ScavengeRequest.options:type_name -> reckon.gateway.v1.ScavengeRequest.OptionsEntry
	31, // 3: reckon.gateway.v1.ScavengeResponse.details:type_name -> reckon.gateway.v1.ScavengeResponse.DetailsEntry
	32, // 4: reckon.gateway.v1.ScavengeMatchingRequest.options:type_name -> reckon.gateway.v1.ScavengeMatchingRequest.OptionsEntry
	8,  // 5: reckon.gateway.v1.ScavengeMatchingResponse.results:type_name -> reckon.gateway.v1.ScavengeResponse
	33, // 6: reckon.gateway.v1.CreateLinkRequest.options:type_name -> reckon.gateway.v1.CreateLinkRequest.OptionsEntry
	34, // 7: reckon.gateway.v1.LinkInfo.options:type_name -> reckon.gateway.v1.LinkInfo.OptionsEntry
	16, // 8: reckon.gateway.v1.ListLinksResponse.links:type_name -> reckon.gateway.v1.LinkInfo
	35, // 9: reckon.gateway.v1.LinkRuntimeInfo.details:type_name -> reckon.gateway.v1.LinkRuntimeInfo.DetailsEntry
	28, // 10: reckon.gateway.v1.GetCatalogueStatusResponse.clusters:type_name -> reckon.gateway.v1.CatalogueClusterStatus
	0,  // 11: reckon.gateway.v1.AdminService.GetStoreStats:input_type -> reckon.gateway.v1.StoreStatsRequest
	2,  // 12: reckon.gateway.v1.AdminService.GetStreamInfo:input_type -> reckon.gateway.v1.StreamInfoRequest
	4,  // 13: reckon.gateway.v1.AdminService.GetEventTypeSummary:input_type -> reckon.gateway.v1.EventTypeSummaryRequest
	7,  // 14: reckon.gateway.v1.AdminService.Scavenge:input_type -> reckon.gateway.v1.ScavengeRequest
	9,  // 15: reckon.gateway.v1.AdminService.ScavengeMatching:input_type -> reckon.gateway.v1.ScavengeMatchingRequest
	7,  // 16: reckon.gateway.v1.AdminService.ScavengeDryRun:input_type -> reckon.gateway.v1.ScavengeRequest
	11, // 17: reckon.gateway.v1.AdminService.CreateLink:input_type -> reckon.gateway.v1.CreateLinkRequest
	13, // 18: reckon.gateway.v1.AdminService.DeleteLink:input_type -> reckon.gateway.v1.DeleteLinkRequest
	15, // 19: reckon.gateway.v1.AdminService.GetLink:input_type -> reckon.gateway.v1.GetLinkRequest
	21, // 20: reckon.gateway.v1.AdminService.ListLinks:input_type -> reckon.gateway.v1.ListLinksRequest
	17, // 21: reckon.gateway.v1.AdminService.StartLink:input_type -> reckon.gateway.v1.StartLinkRequest
	19, // 22: reckon.gateway.v1.AdminService.StopLink:input_type -> reckon.gateway.v1.StopLinkRequest
	15, // 23: reckon.gateway.v1.AdminService.GetLinkInfo:input_type -> reckon.gateway.v1.GetLinkRequest
	24, // 24: reckon.gateway.v1.AdminService.ReloadCatalogue:input_type -> reckon.gateway.v1.ReloadCatalogueRequest
	26, // 25: reckon.gateway.v1.AdminService.GetCatalogueStatus:input_type -> reckon.gateway.v1.GetCatalogueStatusRequest
	1,  // 26: reckon.gateway.v1.AdminService.GetStoreStats:output_type -> reckon.gateway.v1.StoreStatsResponse
	3,  // 27: reckon.gateway.v1.AdminService.GetStreamInfo:output_type -> reckon.gateway.v1.StreamInfoResponse
	6,  // 28: reckon.gateway.v1.AdminService.GetEventTypeSummary:output_type -> reckon.gateway.v1.EventTypeSummaryResponse
	8,  // 29: reckon.gateway.v1.AdminService.Scavenge:output_type -> reckon.gateway.v1.ScavengeResponse
	10, // 30: reckon.gateway.v1.AdminService.ScavengeMatching:output_type -> reckon.gateway.v1.ScavengeMatchingResponse
	8,  // 31: reckon.gateway.v1.AdminService.ScavengeDryRun:output_type -> reckon.gateway.v1.ScavengeResponse
	12, // 32: reckon.gateway.v1.AdminService.CreateLink:output_type -> reckon.gateway.v1.CreateLinkResponse
	14, // 33: reckon.gateway.v1.AdminService.DeleteLink:output_type -> reckon.gateway.v1.DeleteLinkResponse
	16, // 34: reckon.gateway.v1.AdminService.GetLink:output_type -> reckon.gateway.v1.LinkInfo
	22, // 35: reckon.gateway.v1.AdminService.ListLinks:output_type -> reckon.gateway.v1.ListLinksResponse
	18, // 36: reckon.gateway.v1.AdminService.StartLink:output_type -> reckon.gateway.v1.StartLinkResponse
	20, // 37: reckon.gateway.v1.AdminService.StopLink:output_type -> reckon.gateway.v1.StopLinkResponse
	23, // 38: reckon.gateway.v1.AdminService.GetLinkInfo:output_type -> reckon.gateway.v1.LinkRuntimeInfo
	25, // 39: reckon.gateway.v1.AdminService.ReloadCatalogue:output_type -> reckon.gateway.v1.ReloadCatalogueResponse
	27, // 40: reckon.gateway.v1.AdminService.GetCatalogueStatus:output_type -> reckon.gateway.v1.GetCatalogueStatusResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_reckon_admin_proto_init() }
func file_reckon_admin_proto_init() {
	if File_reckon_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_admin_proto_rawDesc), len(file_reckon_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_admin_proto_goTypes,
		DependencyIndexes: file_reckon_admin_proto_depIdxs,
		MessageInfos:      file_reckon_admin_proto_msgTypes,
	}.Build()
	File_reckon_admin_proto = out.File
	file_reckon_admin_proto_goTypes = nil
	file_reckon_admin_proto_depIdxs = nil
}
