// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_temporal.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemporalService_ReadUntil_FullMethodName = "/reckon.gateway.v1.TemporalService/ReadUntil"
	TemporalService_ReadRange_FullMethodName = "/reckon.gateway.v1.TemporalService/ReadRange"
	TemporalService_VersionAt_FullMethodName = "/reckon.gateway.v1.TemporalService/VersionAt"
)

// TemporalServiceClient is the client API for TemporalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TemporalService provides time-based event queries.
//
// Query events by timestamp ranges, useful for debugging,
// auditing, and point-in-time reconstruction.
type TemporalServiceClient interface {
	// Read events from a stream up to a timestamp.
	ReadUntil(ctx context.Context, in *ReadUntilRequest, opts ...grpc.CallOption) (*ReadUntilResponse, error)
	// Read events from a stream within a time range.
	ReadRange(ctx context.Context, in *ReadRangeRequest, opts ...grpc.CallOption) (*ReadRangeResponse, error)
	// Get the stream version at a specific point in time.
	VersionAt(ctx context.Context, in *VersionAtRequest, opts ...grpc.CallOption) (*VersionAtResponse, error)
}

type temporalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemporalServiceClient(cc grpc.ClientConnInterface) TemporalServiceClient {
	return &temporalServiceClient{cc}
}

func (c *temporalServiceClient) ReadUntil(ctx context.Context, in *ReadUntilRequest, opts ...grpc.CallOption) (*ReadUntilResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadUntilResponse)
	err := c.cc.Invoke(ctx, TemporalService_ReadUntil_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) ReadRange(ctx context.Context, in *ReadRangeRequest, opts ...grpc.CallOption) (*ReadRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadRangeResponse)
	err := c.cc.Invoke(ctx, TemporalService_ReadRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) VersionAt(ctx context.Context, in *VersionAtRequest, opts ...grpc.CallOption) (*VersionAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionAtResponse)
	err := c.cc.Invoke(ctx, TemporalService_VersionAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalServiceServer is the server API for TemporalService service.
// All implementations should embed UnimplementedTemporalServiceServer
// for forward compatibility.
//
// TemporalService provides time-based event queries.
//
// Query events by timestamp ranges, useful for debugging,
// auditing, and point-in-time reconstruction.
type TemporalServiceServer interface {
	// Read events from a stream up to a timestamp.
	ReadUntil(context.Context, *ReadUntilRequest) (*ReadUntilResponse, error)
	// Read events from a stream within a time range.
	ReadRange(context.Context, *ReadRangeRequest) (*ReadRangeResponse, error)
	// Get the stream version at a specific point in time.
	VersionAt(context.Context, *VersionAtRequest) (*VersionAtResponse, error)
}

// UnimplementedTemporalServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemporalServiceServer struct{}

func (UnimplementedTemporalServiceServer) ReadUntil(context.Context, *ReadUntilRequest) (*ReadUntilResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadUntil not implemented")
}
func (UnimplementedTemporalServiceServer) ReadRange(context.Context, *ReadRangeRequest) (*ReadRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadRange not implemented")
}
func (UnimplementedTemporalServiceServer) VersionAt(context.Context, *VersionAtRequest) (*VersionAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VersionAt not implemented")
}
func (UnimplementedTemporalServiceServer) testEmbeddedByValue() {}

// UnsafeTemporalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemporalServiceServer will
// result in compilation errors.
type UnsafeTemporalServiceServer interface {
	mustEmbedUnimplementedTemporalServiceServer()
}

func RegisterTemporalServiceServer(s grpc.ServiceRegistrar, srv TemporalServiceServer) {
	// If the following call panics, it indicates UnimplementedTemporalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemporalService_ServiceDesc, srv)
}

func _TemporalService_ReadUntil_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUntilRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).ReadUntil(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_ReadUntil_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).ReadUntil(ctx, req.(*ReadUntilRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_ReadRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).ReadRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_ReadRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).ReadRange(ctx, req.(*ReadRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_VersionAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).VersionAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_VersionAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).VersionAt(ctx, req.(*VersionAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemporalService_ServiceDesc is the grpc.ServiceDesc for TemporalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemporalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.TemporalService",
	HandlerType: (*TemporalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadUntil",
			Handler:    _TemporalService_ReadUntil_Handler,
		},
		{
			MethodName: "ReadRange",
			Handler:    _TemporalService_ReadRange_Handler,
		},
		{
			MethodName: "VersionAt",
			Handler:    _TemporalService_VersionAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reckon_temporal.proto",
}
