// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reckon_streams.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEventsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StoreId  string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Expected version for optimistic concurrency.
	// Use ExpectedVersion constants: NO_STREAM (-1), ANY_VERSION (-2), STREAM_EXISTS (-4).
	ExpectedVersion int64            `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Events          []*ProposedEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendEventsRequest) Reset() {
	*x = AppendEventsRequest{}
	mi := &file_reckon_streams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventsRequest) ProtoMessage() {}

func (x *AppendEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventsRequest.ProtoReflect.Descriptor instead.
func (*AppendEventsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEventsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *AppendEventsRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AppendEventsRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *AppendEventsRequest) GetEvents() []*ProposedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReadStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	StartVersion  uint64                 `protobuf:"varint,3,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	Count         uint64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamRequest) Reset() {
	*x = ReadStreamRequest{}
	mi := &file_reckon_streams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamRequest) ProtoMessage() {}

func (x *ReadStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamRequest.ProtoReflect.Descriptor instead.
func (*ReadStreamRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{1}
}

func (x *ReadStreamRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ReadStreamRequest) GetStartVersion() uint64 {
	if x != nil {
		return x.StartVersion
	}
	return 0
}

func (x *ReadStreamRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetStreamVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamVersionRequest) Reset() {
	*x = GetStreamVersionRequest{}
	mi := &file_reckon_streams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamVersionRequest) ProtoMessage() {}

func (x *GetStreamVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamVersionRequest.ProtoReflect.Descriptor instead.
func (*GetStreamVersionRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{2}
}

func (x *GetStreamVersionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetStreamVersionRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type ListStreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_reckon_streams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{3}
}

func (x *ListStreamsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type DeleteStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamRequest) Reset() {
	*x = DeleteStreamRequest{}
	mi := &file_reckon_streams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamRequest) ProtoMessage() {}

func (x *DeleteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamRequest.ProtoReflect.Descriptor instead.
func (*DeleteStreamRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteStreamRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DeleteStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type ReadByEventTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	EventTypes    []string               `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	BatchSize     uint64                 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadByEventTypesRequest) Reset() {
	*x = ReadByEventTypesRequest{}
	mi := &file_reckon_streams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadByEventTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadByEventTypesRequest) ProtoMessage() {}

func (x *ReadByEventTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadByEventTypesRequest.ProtoReflect.Descriptor instead.
func (*ReadByEventTypesRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{5}
}

func (x *ReadByEventTypesRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadByEventTypesRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *ReadByEventTypesRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReadByTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Match         TagMatch               `protobuf:"varint,3,opt,name=match,proto3,enum=reckon.gateway.v1.TagMatch" json:"match,omitempty"`
	BatchSize     uint64                 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadByTagsRequest) Reset() {
	*x = ReadByTagsRequest{}
	mi := &file_reckon_streams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadByTagsRequest) ProtoMessage() {}

func (x *ReadByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadByTagsRequest.ProtoReflect.Descriptor instead.
func (*ReadByTagsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{6}
}

func (x *ReadByTagsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReadByTagsRequest) GetMatch() TagMatch {
	if x != nil {
		return x.Match
	}
	return TagMatch_TAG_MATCH_ANY
}

func (x *ReadByTagsRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReadAllGlobalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllGlobalRequest) Reset() {
	*x = ReadAllGlobalRequest{}
	mi := &file_reckon_streams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllGlobalRequest) ProtoMessage() {}

func (x *ReadAllGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllGlobalRequest.ProtoReflect.Descriptor instead.
func (*ReadAllGlobalRequest) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{7}
}

func (x *ReadAllGlobalRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadAllGlobalRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadAllGlobalRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AppendEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Position      uint64                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEventsResponse) Reset() {
	*x = AppendEventsResponse{}
	mi := &file_reckon_streams_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEventsResponse) ProtoMessage() {}

func (x *AppendEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEventsResponse.ProtoReflect.Descriptor instead.
func (*AppendEventsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{8}
}

func (x *AppendEventsResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendEventsResponse) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *AppendEventsResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RecordedEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStreamResponse) Reset() {
	*x = ReadStreamResponse{}
	mi := &file_reckon_streams_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStreamResponse) ProtoMessage() {}

func (x *ReadStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStreamResponse.ProtoReflect.Descriptor instead.
func (*ReadStreamResponse) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{9}
}

func (x *ReadStreamResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetStreamVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamVersionResponse) Reset() {
	*x = GetStreamVersionResponse{}
	mi := &file_reckon_streams_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamVersionResponse) ProtoMessage() {}

func (x *GetStreamVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamVersionResponse.ProtoReflect.Descriptor instead.
func (*GetStreamVersionResponse) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamVersionResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamIds     []string               `protobuf:"bytes,1,rep,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_reckon_streams_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{11}
}

func (x *ListStreamsResponse) GetStreamIds() []string {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

type DeleteStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStreamResponse) Reset() {
	*x = DeleteStreamResponse{}
	mi := &file_reckon_streams_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStreamResponse) ProtoMessage() {}

func (x *DeleteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_streams_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStreamResponse.ProtoReflect.Descriptor instead.
func (*DeleteStreamResponse) Descriptor() ([]byte, []int) {
	return file_reckon_streams_proto_rawDescGZIP(), []int{12}
}

var File_reckon_streams_proto protoreflect.FileDescriptor

const file_reckon_streams_proto_rawDesc = "" +
	"\n" +
	"\x14reckon_streams.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"\xb2\x01\n" +
	"\x13AppendEventsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\x128\n" +
	"\x06events\x18\x04 \x03(\v2 .reckon.gateway.v1.ProposedEventR\x06events\"\x86\x01\n" +
	"\x11ReadStreamRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12#\n" +
	"\rstart_version\x18\x03 \x01(\x04R\fstartVersion\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x04R\x05count\"Q\n" +
	"\x17GetStreamVersionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"/\n" +
	"\x12ListStreamsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"M\n" +
	"\x13DeleteStreamRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"t\n" +
	"\x17ReadByEventTypesRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x04R\tbatchSize\"\x94\x01\n" +
	"\x11ReadByTagsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x121\n" +
	"\x05match\x18\x03 \x01(\x0e2\x1b.reckon.gateway.v1.TagMatchR\x05match\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x04R\tbatchSize\"_\n" +
	"\x14ReadAllGlobalRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"b\n" +
	"\x14AppendEventsResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x04R\bposition\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"N\n" +
	"\x12ReadStreamResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\"4\n" +
	"\x18GetStreamVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"4\n" +
	"\x13ListStreamsResponse\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x01 \x03(\tR\tstreamIds\"\x16\n" +
	"\x14DeleteStreamResponse2\xe5\a\n" +
	"\rStreamService\x12_\n" +
	"\fAppendEvents\x12&.reckon.gateway.v1.AppendEventsRequest\x1a'.reckon.gateway.v1.AppendEventsResponse\x12`\n" +
	"\x11ReadStreamForward\x12$.reckon.gateway.v1.ReadStreamRequest\x1a%.reckon.gateway.v1.ReadStreamResponse\x12a\n" +
	"\x12ReadStreamBackward\x12$.reckon.gateway.v1.ReadStreamRequest\x1a%.reckon.gateway.v1.ReadStreamResponse\x12_\n" +
	"\x13StreamEventsForward\x12$.reckon.gateway.v1.ReadStreamRequest\x1a .reckon.gateway.v1.RecordedEvent0\x01\x12k\n" +
	"\x10GetStreamVersion\x12*.reckon.gateway.v1.GetStreamVersionRequest\x1a+.reckon.gateway.v1.GetStreamVersionResponse\x12\\\n" +
	"\vListStreams\x12%.reckon.gateway.v1.ListStreamsRequest\x1a&.reckon.gateway.v1.ListStreamsResponse\x12_\n" +
	"\fDeleteStream\x12&.reckon.gateway.v1.DeleteStreamRequest\x1a'.reckon.gateway.v1.DeleteStreamResponse\x12e\n" +
	"\x10ReadByEventTypes\x12*.reckon.gateway.v1.ReadByEventTypesRequest\x1a%.reckon.gateway.v1.ReadStreamResponse\x12Y\n" +
	"\n" +
	"ReadByTags\x12$.reckon.gateway.v1.ReadByTagsRequest\x1a%.reckon.gateway.v1.ReadStreamResponse\x12_\n" +
	"\rReadAllGlobal\x12'.reckon.gateway.v1.ReadAllGlobalRequest\x1a%.reckon.gateway.v1.ReadStreamResponseBCZAcodeberg.org/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_streams_proto_rawDescOnce sync.Once
	file_reckon_streams_proto_rawDescData []byte
)

func file_reckon_streams_proto_rawDescGZIP() []byte {
	file_reckon_streams_proto_rawDescOnce.Do(func() {
		file_reckon_streams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_streams_proto_rawDesc), len(file_reckon_streams_proto_rawDesc)))
	})
	return file_reckon_streams_proto_rawDescData
}

var file_reckon_streams_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_reckon_streams_proto_goTypes = []any{
	(*AppendEventsRequest)(nil),      // 0: reckon.gateway.v1.AppendEventsRequest
	(*ReadStreamRequest)(nil),        // 1: reckon.gateway.v1.ReadStreamRequest
	(*GetStreamVersionRequest)(nil),  // 2: reckon.gateway.v1.GetStreamVersionRequest
	(*ListStreamsRequest)(nil),       // 3: reckon.gateway.v1.ListStreamsRequest
	(*DeleteStreamRequest)(nil),      // 4: reckon.gateway.v1.DeleteStreamRequest
	(*ReadByEventTypesRequest)(nil),  // 5: reckon.gateway.v1.ReadByEventTypesRequest
	(*ReadByTagsRequest)(nil),        // 6: reckon.gateway.v1.ReadByTagsRequest
	(*ReadAllGlobalRequest)(nil),     // 7: reckon.gateway.v1.ReadAllGlobalRequest
	(*AppendEventsResponse)(nil),     // 8: reckon.gateway.v1.AppendEventsResponse
	(*ReadStreamResponse)(nil),       // 9: reckon.gateway.v1.ReadStreamResponse
	(*GetStreamVersionResponse)(nil), // 10: reckon.gateway.v1.GetStreamVersionResponse
	(*ListStreamsResponse)(nil),      // 11: reckon.gateway.v1.ListStreamsResponse
	(*DeleteStreamResponse)(nil),     // 12: reckon.gateway.v1.DeleteStreamResponse
	(*ProposedEvent)(nil),            // 13: reckon.gateway.v1.ProposedEvent
	(TagMatch)(0),                    // 14: reckon.gateway.v1.TagMatch
	(*RecordedEvent)(nil),            // 15: reckon.gateway.v1.RecordedEvent
}
var file_reckon_streams_proto_depIdxs = []int32{
	13, // 0: reckon.gateway.v1.AppendEventsRequest.events:type_name -> reckon.gateway.v1.ProposedEvent
	14, // 1: reckon.gateway.v1.ReadByTagsRequest.match:type_name -> reckon.gateway.v1.TagMatch
	15, // 2: reckon.gateway.v1.ReadStreamResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	0,  // 3: reckon.gateway.v1.StreamService.AppendEvents:input_type -> reckon.gateway.v1.AppendEventsRequest
	1,  // 4: reckon.gateway.v1.StreamService.ReadStreamForward:input_type -> reckon.gateway.v1.ReadStreamRequest
	1,  // 5: reckon.gateway.v1.StreamService.ReadStreamBackward:input_type -> reckon.gateway.v1.ReadStreamRequest
	1,  // 6: reckon.gateway.v1.StreamService.StreamEventsForward:input_type -> reckon.gateway.v1.ReadStreamRequest
	2,  // 7: reckon.gateway.v1.StreamService.GetStreamVersion:input_type -> reckon.gateway.v1.GetStreamVersionRequest
	3,  // 8: reckon.gateway.v1.StreamService.ListStreams:input_type -> reckon.gateway.v1.ListStreamsRequest
	4,  // 9: reckon.gateway.v1.StreamService.DeleteStream:input_type -> reckon.gateway.v1.DeleteStreamRequest
	5,  // 10: reckon.gateway.v1.StreamService.ReadByEventTypes:input_type -> reckon.gateway.v1.ReadByEventTypesRequest
	6,  // 11: reckon.gateway.v1.StreamService.ReadByTags:input_type -> reckon.gateway.v1.ReadByTagsRequest
	7,  // 12: reckon.gateway.v1.StreamService.ReadAllGlobal:input_type -> reckon.gateway.v1.ReadAllGlobalRequest
	8,  // 13: reckon.gateway.v1.StreamService.AppendEvents:output_type -> reckon.gateway.v1.AppendEventsResponse
	9,  // 14: reckon.gateway.v1.StreamService.ReadStreamForward:output_type -> reckon.gateway.v1.ReadStreamResponse
	9,  // 15: reckon.gateway.v1.StreamService.ReadStreamBackward:output_type -> reckon.gateway.v1.ReadStreamResponse
	15, // 16: reckon.gateway.v1.StreamService.StreamEventsForward:output_type -> reckon.gateway.v1.RecordedEvent
	10, // 17: reckon.gateway.v1.StreamService.GetStreamVersion:output_type -> reckon.gateway.v1.GetStreamVersionResponse
	11, // 18: reckon.gateway.v1.StreamService.ListStreams:output_type -> reckon.gateway.v1.ListStreamsResponse
	12, // 19: reckon.gateway.v1.StreamService.DeleteStream:output_type -> reckon.gateway.v1.DeleteStreamResponse
	9,  // 20: reckon.gateway.v1.StreamService.ReadByEventTypes:output_type -> reckon.gateway.v1.ReadStreamResponse
	9,  // 21: reckon.gateway.v1.StreamService.ReadByTags:output_type -> reckon.gateway.v1.ReadStreamResponse
	9,  // 22: reckon.gateway.v1.StreamService.ReadAllGlobal:output_type -> reckon.gateway.v1.ReadStreamResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reckon_streams_proto_init() }
func file_reckon_streams_proto_init() {
	if File_reckon_streams_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_streams_proto_rawDesc), len(file_reckon_streams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_streams_proto_goTypes,
		DependencyIndexes: file_reckon_streams_proto_depIdxs,
		MessageInfos:      file_reckon_streams_proto_msgTypes,
	}.Build()
	File_reckon_streams_proto = out.File
	file_reckon_streams_proto_goTypes = nil
	file_reckon_streams_proto_depIdxs = nil
}
