// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reckon_temporal.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadUntilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BatchSize     uint64                 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUntilRequest) Reset() {
	*x = ReadUntilRequest{}
	mi := &file_reckon_temporal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUntilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUntilRequest) ProtoMessage() {}

func (x *ReadUntilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUntilRequest.ProtoReflect.Descriptor instead.
func (*ReadUntilRequest) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{0}
}

func (x *ReadUntilRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadUntilRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ReadUntilRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReadUntilRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReadRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	FromTimestamp int64                  `protobuf:"varint,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"`
	ToTimestamp   int64                  `protobuf:"varint,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`
	BatchSize     uint64                 `protobuf:"varint,5,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRangeRequest) Reset() {
	*x = ReadRangeRequest{}
	mi := &file_reckon_temporal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRangeRequest) ProtoMessage() {}

func (x *ReadRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRangeRequest.ProtoReflect.Descriptor instead.
func (*ReadRangeRequest) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{1}
}

func (x *ReadRangeRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadRangeRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ReadRangeRequest) GetFromTimestamp() int64 {
	if x != nil {
		return x.FromTimestamp
	}
	return 0
}

func (x *ReadRangeRequest) GetToTimestamp() int64 {
	if x != nil {
		return x.ToTimestamp
	}
	return 0
}

func (x *ReadRangeRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type VersionAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionAtRequest) Reset() {
	*x = VersionAtRequest{}
	mi := &file_reckon_temporal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionAtRequest) ProtoMessage() {}

func (x *VersionAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionAtRequest.ProtoReflect.Descriptor instead.
func (*VersionAtRequest) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{2}
}

func (x *VersionAtRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *VersionAtRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *VersionAtRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReadUntilResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RecordedEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUntilResponse) Reset() {
	*x = ReadUntilResponse{}
	mi := &file_reckon_temporal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUntilResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUntilResponse) ProtoMessage() {}

func (x *ReadUntilResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUntilResponse.ProtoReflect.Descriptor instead.
func (*ReadUntilResponse) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{3}
}

func (x *ReadUntilResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReadRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RecordedEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRangeResponse) Reset() {
	*x = ReadRangeResponse{}
	mi := &file_reckon_temporal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRangeResponse) ProtoMessage() {}

func (x *ReadRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRangeResponse.ProtoReflect.Descriptor instead.
func (*ReadRangeResponse) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRangeResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type VersionAtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionAtResponse) Reset() {
	*x = VersionAtResponse{}
	mi := &file_reckon_temporal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionAtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionAtResponse) ProtoMessage() {}

func (x *VersionAtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_temporal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionAtResponse.ProtoReflect.Descriptor instead.
func (*VersionAtResponse) Descriptor() ([]byte, []int) {
	return file_reckon_temporal_proto_rawDescGZIP(), []int{5}
}

func (x *VersionAtResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_reckon_temporal_proto protoreflect.FileDescriptor

const file_reckon_temporal_proto_rawDesc = "" +
	"\n" +
	"\x15reckon_temporal.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"\x87\x01\n" +
	"\x10ReadUntilRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x04R\tbatchSize\"\xb3\x01\n" +
	"\x10ReadRangeRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12%\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\x03R\rfromTimestamp\x12!\n" +
	"\fto_timestamp\x18\x04 \x01(\x03R\vtoTimestamp\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x05 \x01(\x04R\tbatchSize\"h\n" +
	"\x10VersionAtRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"M\n" +
	"\x11ReadUntilResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\"M\n" +
	"\x11ReadRangeResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\"-\n" +
	"\x11VersionAtResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion2\x99\x02\n" +
	"\x0fTemporalService\x12V\n" +
	"\tReadUntil\x12#.reckon.gateway.v1.ReadUntilRequest\x1a$.reckon.gateway.v1.ReadUntilResponse\x12V\n" +
	"\tReadRange\x12#.reckon.gateway.v1.ReadRangeRequest\x1a$.reckon.gateway.v1.ReadRangeResponse\x12V\n" +
	"\tVersionAt\x12#.reckon.gateway.v1.VersionAtRequest\x1a$.reckon.gateway.v1.VersionAtResponseBAZ?github.com/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_temporal_proto_rawDescOnce sync.Once
	file_reckon_temporal_proto_rawDescData []byte
)

func file_reckon_temporal_proto_rawDescGZIP() []byte {
	file_reckon_temporal_proto_rawDescOnce.Do(func() {
		file_reckon_temporal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_temporal_proto_rawDesc), len(file_reckon_temporal_proto_rawDesc)))
	})
	return file_reckon_temporal_proto_rawDescData
}

var file_reckon_temporal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_reckon_temporal_proto_goTypes = []any{
	(*ReadUntilRequest)(nil),  // 0: reckon.gateway.v1.ReadUntilRequest
	(*ReadRangeRequest)(nil),  // 1: reckon.gateway.v1.ReadRangeRequest
	(*VersionAtRequest)(nil),  // 2: reckon.gateway.v1.VersionAtRequest
	(*ReadUntilResponse)(nil), // 3: reckon.gateway.v1.ReadUntilResponse
	(*ReadRangeResponse)(nil), // 4: reckon.gateway.v1.ReadRangeResponse
	(*VersionAtResponse)(nil), // 5: reckon.gateway.v1.VersionAtResponse
	(*RecordedEvent)(nil),     // 6: reckon.gateway.v1.RecordedEvent
}
var file_reckon_temporal_proto_depIdxs = []int32{
	6, // 0: reckon.gateway.v1.ReadUntilResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	6, // 1: reckon.gateway.v1.ReadRangeResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	0, // 2: reckon.gateway.v1.TemporalService.ReadUntil:input_type -> reckon.gateway.v1.ReadUntilRequest
	1, // 3: reckon.gateway.v1.TemporalService.ReadRange:input_type -> reckon.gateway.v1.ReadRangeRequest
	2, // 4: reckon.gateway.v1.TemporalService.VersionAt:input_type -> reckon.gateway.v1.VersionAtRequest
	3, // 5: reckon.gateway.v1.TemporalService.ReadUntil:output_type -> reckon.gateway.v1.ReadUntilResponse
	4, // 6: reckon.gateway.v1.TemporalService.ReadRange:output_type -> reckon.gateway.v1.ReadRangeResponse
	5, // 7: reckon.gateway.v1.TemporalService.VersionAt:output_type -> reckon.gateway.v1.VersionAtResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reckon_temporal_proto_init() }
func file_reckon_temporal_proto_init() {
	if File_reckon_temporal_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_temporal_proto_rawDesc), len(file_reckon_temporal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_temporal_proto_goTypes,
		DependencyIndexes: file_reckon_temporal_proto_depIdxs,
		MessageInfos:      file_reckon_temporal_proto_msgTypes,
	}.Build()
	File_reckon_temporal_proto = out.File
	file_reckon_temporal_proto_goTypes = nil
	file_reckon_temporal_proto_depIdxs = nil
}
