// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reckon_shared.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionType int32

const (
	SubscriptionType_SUBSCRIPTION_TYPE_UNSPECIFIED   SubscriptionType = 0
	SubscriptionType_SUBSCRIPTION_TYPE_STREAM        SubscriptionType = 1
	SubscriptionType_SUBSCRIPTION_TYPE_EVENT_TYPE    SubscriptionType = 2
	SubscriptionType_SUBSCRIPTION_TYPE_EVENT_PATTERN SubscriptionType = 3
	SubscriptionType_SUBSCRIPTION_TYPE_EVENT_PAYLOAD SubscriptionType = 4
	SubscriptionType_SUBSCRIPTION_TYPE_TAGS          SubscriptionType = 5
)

// Enum value maps for SubscriptionType.
var (
	SubscriptionType_name = map[int32]string{
		0: "SUBSCRIPTION_TYPE_UNSPECIFIED",
		1: "SUBSCRIPTION_TYPE_STREAM",
		2: "SUBSCRIPTION_TYPE_EVENT_TYPE",
		3: "SUBSCRIPTION_TYPE_EVENT_PATTERN",
		4: "SUBSCRIPTION_TYPE_EVENT_PAYLOAD",
		5: "SUBSCRIPTION_TYPE_TAGS",
	}
	SubscriptionType_value = map[string]int32{
		"SUBSCRIPTION_TYPE_UNSPECIFIED":   0,
		"SUBSCRIPTION_TYPE_STREAM":        1,
		"SUBSCRIPTION_TYPE_EVENT_TYPE":    2,
		"SUBSCRIPTION_TYPE_EVENT_PATTERN": 3,
		"SUBSCRIPTION_TYPE_EVENT_PAYLOAD": 4,
		"SUBSCRIPTION_TYPE_TAGS":          5,
	}
)

func (x SubscriptionType) Enum() *SubscriptionType {
	p := new(SubscriptionType)
	*p = x
	return p
}

func (x SubscriptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_shared_proto_enumTypes[0].Descriptor()
}

func (SubscriptionType) Type() protoreflect.EnumType {
	return &file_reckon_shared_proto_enumTypes[0]
}

func (x SubscriptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionType.Descriptor instead.
func (SubscriptionType) EnumDescriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{0}
}

type TagMatch int32

const (
	TagMatch_TAG_MATCH_ANY TagMatch = 0
	TagMatch_TAG_MATCH_ALL TagMatch = 1
)

// Enum value maps for TagMatch.
var (
	TagMatch_name = map[int32]string{
		0: "TAG_MATCH_ANY",
		1: "TAG_MATCH_ALL",
	}
	TagMatch_value = map[string]int32{
		"TAG_MATCH_ANY": 0,
		"TAG_MATCH_ALL": 1,
	}
)

func (x TagMatch) Enum() *TagMatch {
	p := new(TagMatch)
	*p = x
	return p
}

func (x TagMatch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagMatch) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_shared_proto_enumTypes[1].Descriptor()
}

func (TagMatch) Type() protoreflect.EnumType {
	return &file_reckon_shared_proto_enumTypes[1]
}

func (x TagMatch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagMatch.Descriptor instead.
func (TagMatch) EnumDescriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{1}
}

// ProposedEvent is an event to be appended to a stream.
type ProposedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated event ID (UUID). Server generates one if empty.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event type name (e.g., "user_registered_v1").
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Event payload as JSON bytes.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Event metadata as JSON bytes (correlation_id, causation_id, etc.).
	Metadata []byte `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Optional tags for cross-stream querying.
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Content type of data field. Default: "application/json".
	DataContentType string `protobuf:"bytes,6,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	// Content type of metadata field. Default: "application/json".
	MetadataContentType string `protobuf:"bytes,7,opt,name=metadata_content_type,json=metadataContentType,proto3" json:"metadata_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProposedEvent) Reset() {
	*x = ProposedEvent{}
	mi := &file_reckon_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedEvent) ProtoMessage() {}

func (x *ProposedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedEvent.ProtoReflect.Descriptor instead.
func (*ProposedEvent) Descriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{0}
}

func (x *ProposedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ProposedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProposedEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProposedEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProposedEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProposedEvent) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
	}
	return ""
}

func (x *ProposedEvent) GetMetadataContentType() string {
	if x != nil {
		return x.MetadataContentType
	}
	return ""
}

// RecordedEvent is a persisted event read from a stream.
type RecordedEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventId             string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType           string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	StreamId            string                 `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Version             uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Data                []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata            []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Tags                []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Timestamp           int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EpochUs             int64                  `protobuf:"varint,9,opt,name=epoch_us,json=epochUs,proto3" json:"epoch_us,omitempty"`
	DataContentType     string                 `protobuf:"bytes,10,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	MetadataContentType string                 `protobuf:"bytes,11,opt,name=metadata_content_type,json=metadataContentType,proto3" json:"metadata_content_type,omitempty"`
	// Tamper-resistance fields (added in reckon-gateway 0.2.0,
	// corresponding to reckon-db / reckon-gater 2.1.0).
	//
	// SHA-256 chain hash linking this event back to its predecessor
	// in the same stream. Empty bytes for legacy events written
	// before integrity was enabled for the stream. Polyglot clients
	// can verify chain continuity with their own SHA-256 implementation
	// by walking the events they receive — no shared secret required.
	//
	// The corresponding HMAC field on the storage side is NEVER
	// transmitted: it is a symmetric secret bound to the per-store
	// HMAC key, and leaking it to gateway clients would defeat its
	// purpose. External authenticity (verifiable without the HMAC
	// key) is a future reckon-gateway feature backed by Ed25519
	// signatures.
	PrevEventHash []byte `protobuf:"bytes,12,opt,name=prev_event_hash,json=prevEventHash,proto3" json:"prev_event_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordedEvent) Reset() {
	*x = RecordedEvent{}
	mi := &file_reckon_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordedEvent) ProtoMessage() {}

func (x *RecordedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordedEvent.ProtoReflect.Descriptor instead.
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{1}
}

func (x *RecordedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RecordedEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordedEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *RecordedEvent) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordedEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecordedEvent) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecordedEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecordedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RecordedEvent) GetEpochUs() int64 {
	if x != nil {
		return x.EpochUs
	}
	return 0
}

func (x *RecordedEvent) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
	}
	return ""
}

func (x *RecordedEvent) GetMetadataContentType() string {
	if x != nil {
		return x.MetadataContentType
	}
	return ""
}

func (x *RecordedEvent) GetPrevEventHash() []byte {
	if x != nil {
		return x.PrevEventHash
	}
	return nil
}

type SnapshotRecord struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StreamId  string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Version   uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Data      []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata  []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Timestamp int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Tamper-resistance fields (added in reckon-gateway 0.2.0).
	//
	// SHA-256 chain hash of the event at this snapshot's `version`,
	// captured at snapshot-save time. On the client side, this lets
	// a consumer verify that the snapshot has not been tampered with
	// and that the underlying stream has not been mutated AFTER the
	// snapshot was taken (by recomputing the chain hash at `version`
	// from the events).
	//
	// Empty bytes for legacy snapshots written before integrity was
	// enabled on the store.
	AnchorHash    []byte `protobuf:"bytes,6,opt,name=anchor_hash,json=anchorHash,proto3" json:"anchor_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRecord) Reset() {
	*x = SnapshotRecord{}
	mi := &file_reckon_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRecord) ProtoMessage() {}

func (x *SnapshotRecord) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRecord.ProtoReflect.Descriptor instead.
func (*SnapshotRecord) Descriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotRecord) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SnapshotRecord) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotRecord) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SnapshotRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SnapshotRecord) GetAnchorHash() []byte {
	if x != nil {
		return x.AnchorHash
	}
	return nil
}

type SubscriptionInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type             SubscriptionType       `protobuf:"varint,2,opt,name=type,proto3,enum=reckon.gateway.v1.SubscriptionType" json:"type,omitempty"`
	Selector         string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,4,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PoolSize         uint32                 `protobuf:"varint,6,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	Checkpoint       uint64                 `protobuf:"varint,7,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_reckon_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_reckon_shared_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscriptionInfo) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_TYPE_UNSPECIFIED
}

func (x *SubscriptionInfo) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SubscriptionInfo) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *SubscriptionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SubscriptionInfo) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *SubscriptionInfo) GetCheckpoint() uint64 {
	if x != nil {
		return x.Checkpoint
	}
	return 0
}

var File_reckon_shared_proto protoreflect.FileDescriptor

const file_reckon_shared_proto_rawDesc = "" +
	"\n" +
	"\x13reckon_shared.proto\x12\x11reckon.gateway.v1\"\xed\x01\n" +
	"\rProposedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12*\n" +
	"\x11data_content_type\x18\x06 \x01(\tR\x0fdataContentType\x122\n" +
	"\x15metadata_content_type\x18\a \x01(\tR\x13metadataContentType\"\x85\x03\n" +
	"\rRecordedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\fR\bmetadata\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bepoch_us\x18\t \x01(\x03R\aepochUs\x12*\n" +
	"\x11data_content_type\x18\n" +
	" \x01(\tR\x0fdataContentType\x122\n" +
	"\x15metadata_content_type\x18\v \x01(\tR\x13metadataContentType\x12&\n" +
	"\x0fprev_event_hash\x18\f \x01(\fR\rprevEventHash\"\xb6\x01\n" +
	"\x0eSnapshotRecord\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vanchor_hash\x18\x06 \x01(\fR\n" +
	"anchorHash\"\x80\x02\n" +
	"\x10SubscriptionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.reckon.gateway.v1.SubscriptionTypeR\x04type\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12+\n" +
	"\x11subscription_name\x18\x04 \x01(\tR\x10subscriptionName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tpool_size\x18\x06 \x01(\rR\bpoolSize\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\a \x01(\x04R\n" +
	"checkpoint*\xdb\x01\n" +
	"\x10SubscriptionType\x12!\n" +
	"\x1dSUBSCRIPTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SUBSCRIPTION_TYPE_STREAM\x10\x01\x12 \n" +
	"\x1cSUBSCRIPTION_TYPE_EVENT_TYPE\x10\x02\x12#\n" +
	"\x1fSUBSCRIPTION_TYPE_EVENT_PATTERN\x10\x03\x12#\n" +
	"\x1fSUBSCRIPTION_TYPE_EVENT_PAYLOAD\x10\x04\x12\x1a\n" +
	"\x16SUBSCRIPTION_TYPE_TAGS\x10\x05*0\n" +
	"\bTagMatch\x12\x11\n" +
	"\rTAG_MATCH_ANY\x10\x00\x12\x11\n" +
	"\rTAG_MATCH_ALL\x10\x01BCZAcodeberg.org/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_shared_proto_rawDescOnce sync.Once
	file_reckon_shared_proto_rawDescData []byte
)

func file_reckon_shared_proto_rawDescGZIP() []byte {
	file_reckon_shared_proto_rawDescOnce.Do(func() {
		file_reckon_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_shared_proto_rawDesc), len(file_reckon_shared_proto_rawDesc)))
	})
	return file_reckon_shared_proto_rawDescData
}

var file_reckon_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_reckon_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reckon_shared_proto_goTypes = []any{
	(SubscriptionType)(0),    // 0: reckon.gateway.v1.SubscriptionType
	(TagMatch)(0),            // 1: reckon.gateway.v1.TagMatch
	(*ProposedEvent)(nil),    // 2: reckon.gateway.v1.ProposedEvent
	(*RecordedEvent)(nil),    // 3: reckon.gateway.v1.RecordedEvent
	(*SnapshotRecord)(nil),   // 4: reckon.gateway.v1.SnapshotRecord
	(*SubscriptionInfo)(nil), // 5: reckon.gateway.v1.SubscriptionInfo
}
var file_reckon_shared_proto_depIdxs = []int32{
	0, // 0: reckon.gateway.v1.SubscriptionInfo.type:type_name -> reckon.gateway.v1.SubscriptionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reckon_shared_proto_init() }
func file_reckon_shared_proto_init() {
	if File_reckon_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_shared_proto_rawDesc), len(file_reckon_shared_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reckon_shared_proto_goTypes,
		DependencyIndexes: file_reckon_shared_proto_depIdxs,
		EnumInfos:         file_reckon_shared_proto_enumTypes,
		MessageInfos:      file_reckon_shared_proto_msgTypes,
	}.Build()
	File_reckon_shared_proto = out.File
	file_reckon_shared_proto_goTypes = nil
	file_reckon_shared_proto_depIdxs = nil
}
