// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: reckon_dcb.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TagFilter is a recursive predicate over an event's tag set or type.
//
// Three leaf shapes and two compound shapes:
//
//	match_any:         event matches if it carries ANY of the listed tags
//	match_all:         event matches if it carries ALL of the listed tags
//	event_type_match:  event matches if its event_type equals the value
//	conjunction:       event matches if ALL sub-filters match  (and_)
//	disjunction:       event matches if ANY sub-filter matches (or_)
//
// Names avoid the `and_`/`or_` reserved-word collisions while
// preserving the Erlang term semantics one-to-one:
//
//	match_any         <-> {any_of,     [Tag]}
//	match_all         <-> {all_of,     [Tag]}
//	event_type_match  <-> {event_type, binary()}
//	conjunction       <-> {and_,       [TagFilter]}
//	disjunction       <-> {or_,        [TagFilter]}
//
// Requires backing ReckonDB 5.2.0+ for event_type_match (the
// [by_event_type] index was added in that release). Older backings
// will evaluate the filter correctly only for events written after
// the upgrade; pre-5.2.0 events have no index entry.
type TagFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TagFilter_MatchAny
	//	*TagFilter_MatchAll
	//	*TagFilter_Conjunction
	//	*TagFilter_Disjunction
	//	*TagFilter_EventTypeMatch
	Kind          isTagFilter_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagFilter) Reset() {
	*x = TagFilter{}
	mi := &file_reckon_dcb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilter) ProtoMessage() {}

func (x *TagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilter.ProtoReflect.Descriptor instead.
func (*TagFilter) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{0}
}

func (x *TagFilter) GetKind() isTagFilter_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TagFilter) GetMatchAny() *TagList {
	if x != nil {
		if x, ok := x.Kind.(*TagFilter_MatchAny); ok {
			return x.MatchAny
		}
	}
	return nil
}

func (x *TagFilter) GetMatchAll() *TagList {
	if x != nil {
		if x, ok := x.Kind.(*TagFilter_MatchAll); ok {
			return x.MatchAll
		}
	}
	return nil
}

func (x *TagFilter) GetConjunction() *FilterList {
	if x != nil {
		if x, ok := x.Kind.(*TagFilter_Conjunction); ok {
			return x.Conjunction
		}
	}
	return nil
}

func (x *TagFilter) GetDisjunction() *FilterList {
	if x != nil {
		if x, ok := x.Kind.(*TagFilter_Disjunction); ok {
			return x.Disjunction
		}
	}
	return nil
}

func (x *TagFilter) GetEventTypeMatch() string {
	if x != nil {
		if x, ok := x.Kind.(*TagFilter_EventTypeMatch); ok {
			return x.EventTypeMatch
		}
	}
	return ""
}

type isTagFilter_Kind interface {
	isTagFilter_Kind()
}

type TagFilter_MatchAny struct {
	MatchAny *TagList `protobuf:"bytes,1,opt,name=match_any,json=matchAny,proto3,oneof"`
}

type TagFilter_MatchAll struct {
	MatchAll *TagList `protobuf:"bytes,2,opt,name=match_all,json=matchAll,proto3,oneof"`
}

type TagFilter_Conjunction struct {
	Conjunction *FilterList `protobuf:"bytes,3,opt,name=conjunction,proto3,oneof"`
}

type TagFilter_Disjunction struct {
	Disjunction *FilterList `protobuf:"bytes,4,opt,name=disjunction,proto3,oneof"`
}

type TagFilter_EventTypeMatch struct {
	EventTypeMatch string `protobuf:"bytes,5,opt,name=event_type_match,json=eventTypeMatch,proto3,oneof"`
}

func (*TagFilter_MatchAny) isTagFilter_Kind() {}

func (*TagFilter_MatchAll) isTagFilter_Kind() {}

func (*TagFilter_Conjunction) isTagFilter_Kind() {}

func (*TagFilter_Disjunction) isTagFilter_Kind() {}

func (*TagFilter_EventTypeMatch) isTagFilter_Kind() {}

type TagList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagList) Reset() {
	*x = TagList{}
	mi := &file_reckon_dcb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagList) ProtoMessage() {}

func (x *TagList) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagList.ProtoReflect.Descriptor instead.
func (*TagList) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{1}
}

func (x *TagList) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FilterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*TagFilter           `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterList) Reset() {
	*x = FilterList{}
	mi := &file_reckon_dcb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterList) ProtoMessage() {}

func (x *FilterList) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterList.ProtoReflect.Descriptor instead.
func (*FilterList) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{2}
}

func (x *FilterList) GetFilters() []*TagFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AppendIfNoTagMatchesRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StoreId string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// Consistency context query. Server rejects the write if any
	// event matching this filter has seq > seq_cutoff.
	TagFilter *TagFilter `protobuf:"bytes,2,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	// Highest seq the caller observed for events matching tag_filter
	// when it built the decision. Use -1 if the caller saw nothing.
	//
	// Signed (sint64 ZigZag-encoded) so the -1 sentinel is one byte.
	SeqCutoff int64 `protobuf:"zigzag64,3,opt,name=seq_cutoff,json=seqCutoff,proto3" json:"seq_cutoff,omitempty"`
	// Events to append on success. Same shape as
	// StreamService.AppendEvents.events. Events automatically carry
	// the DCB pseudo-stream id server-side; clients do not set it.
	Events        []*ProposedEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendIfNoTagMatchesRequest) Reset() {
	*x = AppendIfNoTagMatchesRequest{}
	mi := &file_reckon_dcb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendIfNoTagMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendIfNoTagMatchesRequest) ProtoMessage() {}

func (x *AppendIfNoTagMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendIfNoTagMatchesRequest.ProtoReflect.Descriptor instead.
func (*AppendIfNoTagMatchesRequest) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{3}
}

func (x *AppendIfNoTagMatchesRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *AppendIfNoTagMatchesRequest) GetTagFilter() *TagFilter {
	if x != nil {
		return x.TagFilter
	}
	return nil
}

func (x *AppendIfNoTagMatchesRequest) GetSeqCutoff() int64 {
	if x != nil {
		return x.SeqCutoff
	}
	return 0
}

func (x *AppendIfNoTagMatchesRequest) GetEvents() []*ProposedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AppendIfNoTagMatchesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server returns one of two structured outcomes. Both are
	// "request was evaluated successfully"; the conflict is not a
	// protocol error. Network / server errors still come back as
	// gRPC status (UNAVAILABLE, INTERNAL, UNIMPLEMENTED, etc.).
	//
	// Types that are valid to be assigned to Result:
	//
	//	*AppendIfNoTagMatchesResponse_Committed
	//	*AppendIfNoTagMatchesResponse_Conflict
	Result        isAppendIfNoTagMatchesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendIfNoTagMatchesResponse) Reset() {
	*x = AppendIfNoTagMatchesResponse{}
	mi := &file_reckon_dcb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendIfNoTagMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendIfNoTagMatchesResponse) ProtoMessage() {}

func (x *AppendIfNoTagMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendIfNoTagMatchesResponse.ProtoReflect.Descriptor instead.
func (*AppendIfNoTagMatchesResponse) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{4}
}

func (x *AppendIfNoTagMatchesResponse) GetResult() isAppendIfNoTagMatchesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AppendIfNoTagMatchesResponse) GetCommitted() *Committed {
	if x != nil {
		if x, ok := x.Result.(*AppendIfNoTagMatchesResponse_Committed); ok {
			return x.Committed
		}
	}
	return nil
}

func (x *AppendIfNoTagMatchesResponse) GetConflict() *Conflict {
	if x != nil {
		if x, ok := x.Result.(*AppendIfNoTagMatchesResponse_Conflict); ok {
			return x.Conflict
		}
	}
	return nil
}

type isAppendIfNoTagMatchesResponse_Result interface {
	isAppendIfNoTagMatchesResponse_Result()
}

type AppendIfNoTagMatchesResponse_Committed struct {
	Committed *Committed `protobuf:"bytes,1,opt,name=committed,proto3,oneof"`
}

type AppendIfNoTagMatchesResponse_Conflict struct {
	Conflict *Conflict `protobuf:"bytes,2,opt,name=conflict,proto3,oneof"`
}

func (*AppendIfNoTagMatchesResponse_Committed) isAppendIfNoTagMatchesResponse_Result() {}

func (*AppendIfNoTagMatchesResponse_Conflict) isAppendIfNoTagMatchesResponse_Result() {}

// Committed: the conditional-append succeeded.
type Committed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last seq assigned to the appended batch. Subsequent
	// AppendIfNoTagMatches calls by the same caller can use this
	// as their seq_cutoff for follow-up writes against an overlapping
	// tag set.
	LastSeq       uint64 `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Committed) Reset() {
	*x = Committed{}
	mi := &file_reckon_dcb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Committed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Committed) ProtoMessage() {}

func (x *Committed) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Committed.ProtoReflect.Descriptor instead.
func (*Committed) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{5}
}

func (x *Committed) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// Conflict: tag_filter matched at least one event with seq > seq_cutoff.
type Conflict struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest seq the server observed for events matching tag_filter.
	// Callers retrying with a fresh context should refresh their
	// cutoff to this value (or to a higher one obtained by re-reading
	// via ReadDcbContext).
	MaxSeq        uint64 `protobuf:"varint,1,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_reckon_dcb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{6}
}

func (x *Conflict) GetMaxSeq() uint64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type ReadDcbContextRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StoreId   string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	TagFilter *TagFilter             `protobuf:"bytes,2,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	// Cap on returned events. Server may return fewer. A batch_size
	// of 0 lets the server pick a sensible default.
	BatchSize     uint64 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDcbContextRequest) Reset() {
	*x = ReadDcbContextRequest{}
	mi := &file_reckon_dcb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDcbContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDcbContextRequest) ProtoMessage() {}

func (x *ReadDcbContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDcbContextRequest.ProtoReflect.Descriptor instead.
func (*ReadDcbContextRequest) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{7}
}

func (x *ReadDcbContextRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReadDcbContextRequest) GetTagFilter() *TagFilter {
	if x != nil {
		return x.TagFilter
	}
	return nil
}

func (x *ReadDcbContextRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type ReadDcbContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events matching tag_filter, scoped to the DCB pseudo-stream,
	// ordered by seq ascending.
	Events []*RecordedEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Highest seq observed across the returned events. Callers should
	// use this as seq_cutoff in a subsequent AppendIfNoTagMatches.
	// Set to -1 (sint64) when the result set is empty.
	MaxSeq        int64 `protobuf:"zigzag64,2,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDcbContextResponse) Reset() {
	*x = ReadDcbContextResponse{}
	mi := &file_reckon_dcb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDcbContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDcbContextResponse) ProtoMessage() {}

func (x *ReadDcbContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDcbContextResponse.ProtoReflect.Descriptor instead.
func (*ReadDcbContextResponse) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{8}
}

func (x *ReadDcbContextResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReadDcbContextResponse) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

type CccReadByPayloadRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StoreId string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// JSON data field name to match against. Must be indexed via
	// store_config.indexes [{ccc, key}].
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value the field must equal (string comparison after JSON decode).
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Cap on returned events. Server may return fewer. 0 lets the
	// server pick a sensible default.
	BatchSize     uint64 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CccReadByPayloadRequest) Reset() {
	*x = CccReadByPayloadRequest{}
	mi := &file_reckon_dcb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CccReadByPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CccReadByPayloadRequest) ProtoMessage() {}

func (x *CccReadByPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CccReadByPayloadRequest.ProtoReflect.Descriptor instead.
func (*CccReadByPayloadRequest) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{9}
}

func (x *CccReadByPayloadRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CccReadByPayloadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CccReadByPayloadRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CccReadByPayloadRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type CccReadByPayloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events whose data[key] == value, ordered by position ascending.
	Events        []*RecordedEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CccReadByPayloadResponse) Reset() {
	*x = CccReadByPayloadResponse{}
	mi := &file_reckon_dcb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CccReadByPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CccReadByPayloadResponse) ProtoMessage() {}

func (x *CccReadByPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CccReadByPayloadResponse.ProtoReflect.Descriptor instead.
func (*CccReadByPayloadResponse) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{10}
}

func (x *CccReadByPayloadResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CccReadByPayloadHashRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StoreId string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// Field names to include in the combo hash. Order is significant
	// and must match the index declaration in store_config.indexes
	// [{ccc_hash, keys}].
	Keys []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// Values the corresponding fields must equal. Must be the same
	// length as keys.
	Values []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	// Cap on returned events. 0 lets the server pick a default.
	BatchSize     uint64 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CccReadByPayloadHashRequest) Reset() {
	*x = CccReadByPayloadHashRequest{}
	mi := &file_reckon_dcb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CccReadByPayloadHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CccReadByPayloadHashRequest) ProtoMessage() {}

func (x *CccReadByPayloadHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CccReadByPayloadHashRequest.ProtoReflect.Descriptor instead.
func (*CccReadByPayloadHashRequest) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{11}
}

func (x *CccReadByPayloadHashRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CccReadByPayloadHashRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *CccReadByPayloadHashRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *CccReadByPayloadHashRequest) GetBatchSize() uint64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type CccReadByPayloadHashResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events whose payload combo hash matches, ordered by position ascending.
	Events        []*RecordedEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CccReadByPayloadHashResponse) Reset() {
	*x = CccReadByPayloadHashResponse{}
	mi := &file_reckon_dcb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CccReadByPayloadHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CccReadByPayloadHashResponse) ProtoMessage() {}

func (x *CccReadByPayloadHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_dcb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CccReadByPayloadHashResponse.ProtoReflect.Descriptor instead.
func (*CccReadByPayloadHashResponse) Descriptor() ([]byte, []int) {
	return file_reckon_dcb_proto_rawDescGZIP(), []int{12}
}

func (x *CccReadByPayloadHashResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_reckon_dcb_proto protoreflect.FileDescriptor

const file_reckon_dcb_proto_rawDesc = "" +
	"\n" +
	"\x10reckon_dcb.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"\xbb\x02\n" +
	"\tTagFilter\x129\n" +
	"\tmatch_any\x18\x01 \x01(\v2\x1a.reckon.gateway.v1.TagListH\x00R\bmatchAny\x129\n" +
	"\tmatch_all\x18\x02 \x01(\v2\x1a.reckon.gateway.v1.TagListH\x00R\bmatchAll\x12A\n" +
	"\vconjunction\x18\x03 \x01(\v2\x1d.reckon.gateway.v1.FilterListH\x00R\vconjunction\x12A\n" +
	"\vdisjunction\x18\x04 \x01(\v2\x1d.reckon.gateway.v1.FilterListH\x00R\vdisjunction\x12*\n" +
	"\x10event_type_match\x18\x05 \x01(\tH\x00R\x0eeventTypeMatchB\x06\n" +
	"\x04kind\"\x1d\n" +
	"\aTagList\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"D\n" +
	"\n" +
	"FilterList\x126\n" +
	"\afilters\x18\x01 \x03(\v2\x1c.reckon.gateway.v1.TagFilterR\afilters\"\xce\x01\n" +
	"\x1bAppendIfNoTagMatchesRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12;\n" +
	"\n" +
	"tag_filter\x18\x02 \x01(\v2\x1c.reckon.gateway.v1.TagFilterR\ttagFilter\x12\x1d\n" +
	"\n" +
	"seq_cutoff\x18\x03 \x01(\x12R\tseqCutoff\x128\n" +
	"\x06events\x18\x04 \x03(\v2 .reckon.gateway.v1.ProposedEventR\x06events\"\xa1\x01\n" +
	"\x1cAppendIfNoTagMatchesResponse\x12<\n" +
	"\tcommitted\x18\x01 \x01(\v2\x1c.reckon.gateway.v1.CommittedH\x00R\tcommitted\x129\n" +
	"\bconflict\x18\x02 \x01(\v2\x1b.reckon.gateway.v1.ConflictH\x00R\bconflictB\b\n" +
	"\x06result\"&\n" +
	"\tCommitted\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x04R\alastSeq\"#\n" +
	"\bConflict\x12\x17\n" +
	"\amax_seq\x18\x01 \x01(\x04R\x06maxSeq\"\x8e\x01\n" +
	"\x15ReadDcbContextRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12;\n" +
	"\n" +
	"tag_filter\x18\x02 \x01(\v2\x1c.reckon.gateway.v1.TagFilterR\ttagFilter\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x04R\tbatchSize\"k\n" +
	"\x16ReadDcbContextResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\x12\x17\n" +
	"\amax_seq\x18\x02 \x01(\x12R\x06maxSeq\"{\n" +
	"\x17CccReadByPayloadRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x04R\tbatchSize\"T\n" +
	"\x18CccReadByPayloadResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\"\x83\x01\n" +
	"\x1bCccReadByPayloadHashRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\tR\x04keys\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x04R\tbatchSize\"X\n" +
	"\x1cCccReadByPayloadHashResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events2\xd2\x03\n" +
	"\n" +
	"DcbService\x12w\n" +
	"\x14AppendIfNoTagMatches\x12..reckon.gateway.v1.AppendIfNoTagMatchesRequest\x1a/.reckon.gateway.v1.AppendIfNoTagMatchesResponse\x12e\n" +
	"\x0eReadDcbContext\x12(.reckon.gateway.v1.ReadDcbContextRequest\x1a).reckon.gateway.v1.ReadDcbContextResponse\x12k\n" +
	"\x10CccReadByPayload\x12*.reckon.gateway.v1.CccReadByPayloadRequest\x1a+.reckon.gateway.v1.CccReadByPayloadResponse\x12w\n" +
	"\x14CccReadByPayloadHash\x12..reckon.gateway.v1.CccReadByPayloadHashRequest\x1a/.reckon.gateway.v1.CccReadByPayloadHashResponseBAZ?github.com/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_dcb_proto_rawDescOnce sync.Once
	file_reckon_dcb_proto_rawDescData []byte
)

func file_reckon_dcb_proto_rawDescGZIP() []byte {
	file_reckon_dcb_proto_rawDescOnce.Do(func() {
		file_reckon_dcb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_dcb_proto_rawDesc), len(file_reckon_dcb_proto_rawDesc)))
	})
	return file_reckon_dcb_proto_rawDescData
}

var file_reckon_dcb_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_reckon_dcb_proto_goTypes = []any{
	(*TagFilter)(nil),                    // 0: reckon.gateway.v1.TagFilter
	(*TagList)(nil),                      // 1: reckon.gateway.v1.TagList
	(*FilterList)(nil),                   // 2: reckon.gateway.v1.FilterList
	(*AppendIfNoTagMatchesRequest)(nil),  // 3: reckon.gateway.v1.AppendIfNoTagMatchesRequest
	(*AppendIfNoTagMatchesResponse)(nil), // 4: reckon.gateway.v1.AppendIfNoTagMatchesResponse
	(*Committed)(nil),                    // 5: reckon.gateway.v1.Committed
	(*Conflict)(nil),                     // 6: reckon.gateway.v1.Conflict
	(*ReadDcbContextRequest)(nil),        // 7: reckon.gateway.v1.ReadDcbContextRequest
	(*ReadDcbContextResponse)(nil),       // 8: reckon.gateway.v1.ReadDcbContextResponse
	(*CccReadByPayloadRequest)(nil),      // 9: reckon.gateway.v1.CccReadByPayloadRequest
	(*CccReadByPayloadResponse)(nil),     // 10: reckon.gateway.v1.CccReadByPayloadResponse
	(*CccReadByPayloadHashRequest)(nil),  // 11: reckon.gateway.v1.CccReadByPayloadHashRequest
	(*CccReadByPayloadHashResponse)(nil), // 12: reckon.gateway.v1.CccReadByPayloadHashResponse
	(*ProposedEvent)(nil),                // 13: reckon.gateway.v1.ProposedEvent
	(*RecordedEvent)(nil),                // 14: reckon.gateway.v1.RecordedEvent
}
var file_reckon_dcb_proto_depIdxs = []int32{
	1,  // 0: reckon.gateway.v1.TagFilter.match_any:type_name -> reckon.gateway.v1.TagList
	1,  // 1: reckon.gateway.v1.TagFilter.match_all:type_name -> reckon.gateway.v1.TagList
	2,  // 2: reckon.gateway.v1.TagFilter.conjunction:type_name -> reckon.gateway.v1.FilterList
	2,  // 3: reckon.gateway.v1.TagFilter.disjunction:type_name -> reckon.gateway.v1.FilterList
	0,  // 4: reckon.gateway.v1.FilterList.filters:type_name -> reckon.gateway.v1.TagFilter
	0,  // 5: reckon.gateway.v1.AppendIfNoTagMatchesRequest.tag_filter:type_name -> reckon.gateway.v1.TagFilter
	13, // 6: reckon.gateway.v1.AppendIfNoTagMatchesRequest.events:type_name -> reckon.gateway.v1.ProposedEvent
	5,  // 7: reckon.gateway.v1.AppendIfNoTagMatchesResponse.committed:type_name -> reckon.gateway.v1.Committed
	6,  // 8: reckon.gateway.v1.AppendIfNoTagMatchesResponse.conflict:type_name -> reckon.gateway.v1.Conflict
	0,  // 9: reckon.gateway.v1.ReadDcbContextRequest.tag_filter:type_name -> reckon.gateway.v1.TagFilter
	14, // 10: reckon.gateway.v1.ReadDcbContextResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	14, // 11: reckon.gateway.v1.CccReadByPayloadResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	14, // 12: reckon.gateway.v1.CccReadByPayloadHashResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	3,  // 13: reckon.gateway.v1.DcbService.AppendIfNoTagMatches:input_type -> reckon.gateway.v1.AppendIfNoTagMatchesRequest
	7,  // 14: reckon.gateway.v1.DcbService.ReadDcbContext:input_type -> reckon.gateway.v1.ReadDcbContextRequest
	9,  // 15: reckon.gateway.v1.DcbService.CccReadByPayload:input_type -> reckon.gateway.v1.CccReadByPayloadRequest
	11, // 16: reckon.gateway.v1.DcbService.CccReadByPayloadHash:input_type -> reckon.gateway.v1.CccReadByPayloadHashRequest
	4,  // 17: reckon.gateway.v1.DcbService.AppendIfNoTagMatches:output_type -> reckon.gateway.v1.AppendIfNoTagMatchesResponse
	8,  // 18: reckon.gateway.v1.DcbService.ReadDcbContext:output_type -> reckon.gateway.v1.ReadDcbContextResponse
	10, // 19: reckon.gateway.v1.DcbService.CccReadByPayload:output_type -> reckon.gateway.v1.CccReadByPayloadResponse
	12, // 20: reckon.gateway.v1.DcbService.CccReadByPayloadHash:output_type -> reckon.gateway.v1.CccReadByPayloadHashResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_reckon_dcb_proto_init() }
func file_reckon_dcb_proto_init() {
	if File_reckon_dcb_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	file_reckon_dcb_proto_msgTypes[0].OneofWrappers = []any{
		(*TagFilter_MatchAny)(nil),
		(*TagFilter_MatchAll)(nil),
		(*TagFilter_Conjunction)(nil),
		(*TagFilter_Disjunction)(nil),
		(*TagFilter_EventTypeMatch)(nil),
	}
	file_reckon_dcb_proto_msgTypes[4].OneofWrappers = []any{
		(*AppendIfNoTagMatchesResponse_Committed)(nil),
		(*AppendIfNoTagMatchesResponse_Conflict)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_dcb_proto_rawDesc), len(file_reckon_dcb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_dcb_proto_goTypes,
		DependencyIndexes: file_reckon_dcb_proto_depIdxs,
		MessageInfos:      file_reckon_dcb_proto_msgTypes,
	}.Build()
	File_reckon_dcb_proto = out.File
	file_reckon_dcb_proto_goTypes = nil
	file_reckon_dcb_proto_depIdxs = nil
}
