// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reckon_stores.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreEventType int32

const (
	StoreEventType_STORE_EVENT_TYPE_UNSPECIFIED StoreEventType = 0
	StoreEventType_STORE_EVENT_TYPE_ANNOUNCED   StoreEventType = 1 // store newly registered on a node
	StoreEventType_STORE_EVENT_TYPE_RETIRED     StoreEventType = 2 // store unregistered (node down or
)

// Enum value maps for StoreEventType.
var (
	StoreEventType_name = map[int32]string{
		0: "STORE_EVENT_TYPE_UNSPECIFIED",
		1: "STORE_EVENT_TYPE_ANNOUNCED",
		2: "STORE_EVENT_TYPE_RETIRED",
	}
	StoreEventType_value = map[string]int32{
		"STORE_EVENT_TYPE_UNSPECIFIED": 0,
		"STORE_EVENT_TYPE_ANNOUNCED":   1,
		"STORE_EVENT_TYPE_RETIRED":     2,
	}
)

func (x StoreEventType) Enum() *StoreEventType {
	p := new(StoreEventType)
	*p = x
	return p
}

func (x StoreEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_stores_proto_enumTypes[0].Descriptor()
}

func (StoreEventType) Type() protoreflect.EnumType {
	return &file_reckon_stores_proto_enumTypes[0]
}

func (x StoreEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreEventType.Descriptor instead.
func (StoreEventType) EnumDescriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{0}
}

type StoreMode int32

const (
	StoreMode_STORE_MODE_UNSPECIFIED StoreMode = 0
	StoreMode_STORE_MODE_SINGLE      StoreMode = 1 // single-node, no cluster
	StoreMode_STORE_MODE_CLUSTER     StoreMode = 2 // clustered via Raft
)

// Enum value maps for StoreMode.
var (
	StoreMode_name = map[int32]string{
		0: "STORE_MODE_UNSPECIFIED",
		1: "STORE_MODE_SINGLE",
		2: "STORE_MODE_CLUSTER",
	}
	StoreMode_value = map[string]int32{
		"STORE_MODE_UNSPECIFIED": 0,
		"STORE_MODE_SINGLE":      1,
		"STORE_MODE_CLUSTER":     2,
	}
)

func (x StoreMode) Enum() *StoreMode {
	p := new(StoreMode)
	*p = x
	return p
}

func (x StoreMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StoreMode) Descriptor() protoreflect.EnumDescriptor {
	return file_reckon_stores_proto_enumTypes[1].Descriptor()
}

func (StoreMode) Type() protoreflect.EnumType {
	return &file_reckon_stores_proto_enumTypes[1]
}

func (x StoreMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StoreMode.Descriptor instead.
func (StoreMode) EnumDescriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{1}
}

type ListStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_reckon_stores_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{0}
}

type ListStoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*StoreInstance       `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	mi := &file_reckon_stores_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{1}
}

func (x *ListStoresResponse) GetInstances() []*StoreInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type GetStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_reckon_stores_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoreRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetStoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per node currently announcing this store.
	// Empty list means no node is currently hosting it.
	Instances     []*StoreInstance `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_reckon_stores_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoreResponse) GetInstances() []*StoreInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type WatchStoresRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, emit the current snapshot (one STORE_ANNOUNCED per
	// currently-known instance) before going live. Default true.
	IncludeSnapshot bool `protobuf:"varint,1,opt,name=include_snapshot,json=includeSnapshot,proto3" json:"include_snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchStoresRequest) Reset() {
	*x = WatchStoresRequest{}
	mi := &file_reckon_stores_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStoresRequest) ProtoMessage() {}

func (x *WatchStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStoresRequest.ProtoReflect.Descriptor instead.
func (*WatchStoresRequest) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{4}
}

func (x *WatchStoresRequest) GetIncludeSnapshot() bool {
	if x != nil {
		return x.IncludeSnapshot
	}
	return false
}

type StoreEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          StoreEventType         `protobuf:"varint,1,opt,name=type,proto3,enum=reckon.gateway.v1.StoreEventType" json:"type,omitempty"`
	Instance      *StoreInstance         `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	EventAtUs     int64                  `protobuf:"varint,3,opt,name=event_at_us,json=eventAtUs,proto3" json:"event_at_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreEvent) Reset() {
	*x = StoreEvent{}
	mi := &file_reckon_stores_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreEvent) ProtoMessage() {}

func (x *StoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreEvent.ProtoReflect.Descriptor instead.
func (*StoreEvent) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{5}
}

func (x *StoreEvent) GetType() StoreEventType {
	if x != nil {
		return x.Type
	}
	return StoreEventType_STORE_EVENT_TYPE_UNSPECIFIED
}

func (x *StoreEvent) GetInstance() *StoreInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *StoreEvent) GetEventAtUs() int64 {
	if x != nil {
		return x.EventAtUs
	}
	return 0
}

// A single (store_id, node) registration as observed by this gateway.
type StoreInstance struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StoreId        string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Node           string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"` // erlang node name as a string
	Mode           StoreMode              `protobuf:"varint,3,opt,name=mode,proto3,enum=reckon.gateway.v1.StoreMode" json:"mode,omitempty"`
	DataDir        string                 `protobuf:"bytes,4,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	TimeoutMs      uint32                 `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	RegisteredAtUs int64                  `protobuf:"varint,6,opt,name=registered_at_us,json=registeredAtUs,proto3" json:"registered_at_us,omitempty"` // when this entry was first registered
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreInstance) Reset() {
	*x = StoreInstance{}
	mi := &file_reckon_stores_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInstance) ProtoMessage() {}

func (x *StoreInstance) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_stores_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInstance.ProtoReflect.Descriptor instead.
func (*StoreInstance) Descriptor() ([]byte, []int) {
	return file_reckon_stores_proto_rawDescGZIP(), []int{6}
}

func (x *StoreInstance) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *StoreInstance) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *StoreInstance) GetMode() StoreMode {
	if x != nil {
		return x.Mode
	}
	return StoreMode_STORE_MODE_UNSPECIFIED
}

func (x *StoreInstance) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *StoreInstance) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *StoreInstance) GetRegisteredAtUs() int64 {
	if x != nil {
		return x.RegisteredAtUs
	}
	return 0
}

var File_reckon_stores_proto protoreflect.FileDescriptor

const file_reckon_stores_proto_rawDesc = "" +
	"\n" +
	"\x13reckon_stores.proto\x12\x11reckon.gateway.v1\"\x13\n" +
	"\x11ListStoresRequest\"T\n" +
	"\x12ListStoresResponse\x12>\n" +
	"\tinstances\x18\x01 \x03(\v2 .reckon.gateway.v1.StoreInstanceR\tinstances\",\n" +
	"\x0fGetStoreRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"R\n" +
	"\x10GetStoreResponse\x12>\n" +
	"\tinstances\x18\x01 \x03(\v2 .reckon.gateway.v1.StoreInstanceR\tinstances\"?\n" +
	"\x12WatchStoresRequest\x12)\n" +
	"\x10include_snapshot\x18\x01 \x01(\bR\x0fincludeSnapshot\"\xa1\x01\n" +
	"\n" +
	"StoreEvent\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.reckon.gateway.v1.StoreEventTypeR\x04type\x12<\n" +
	"\binstance\x18\x02 \x01(\v2 .reckon.gateway.v1.StoreInstanceR\binstance\x12\x1e\n" +
	"\vevent_at_us\x18\x03 \x01(\x03R\teventAtUs\"\xd4\x01\n" +
	"\rStoreInstance\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x120\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x1c.reckon.gateway.v1.StoreModeR\x04mode\x12\x19\n" +
	"\bdata_dir\x18\x04 \x01(\tR\adataDir\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\rR\ttimeoutMs\x12(\n" +
	"\x10registered_at_us\x18\x06 \x01(\x03R\x0eregisteredAtUs*p\n" +
	"\x0eStoreEventType\x12 \n" +
	"\x1cSTORE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSTORE_EVENT_TYPE_ANNOUNCED\x10\x01\x12\x1c\n" +
	"\x18STORE_EVENT_TYPE_RETIRED\x10\x02*V\n" +
	"\tStoreMode\x12\x1a\n" +
	"\x16STORE_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STORE_MODE_SINGLE\x10\x01\x12\x16\n" +
	"\x12STORE_MODE_CLUSTER\x10\x022\x96\x02\n" +
	"\rStoresService\x12Y\n" +
	"\n" +
	"ListStores\x12$.reckon.gateway.v1.ListStoresRequest\x1a%.reckon.gateway.v1.ListStoresResponse\x12S\n" +
	"\bGetStore\x12\".reckon.gateway.v1.GetStoreRequest\x1a#.reckon.gateway.v1.GetStoreResponse\x12U\n" +
	"\vWatchStores\x12%.reckon.gateway.v1.WatchStoresRequest\x1a\x1d.reckon.gateway.v1.StoreEvent0\x01BCZAcodeberg.org/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_stores_proto_rawDescOnce sync.Once
	file_reckon_stores_proto_rawDescData []byte
)

func file_reckon_stores_proto_rawDescGZIP() []byte {
	file_reckon_stores_proto_rawDescOnce.Do(func() {
		file_reckon_stores_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_stores_proto_rawDesc), len(file_reckon_stores_proto_rawDesc)))
	})
	return file_reckon_stores_proto_rawDescData
}

var file_reckon_stores_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_reckon_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_reckon_stores_proto_goTypes = []any{
	(StoreEventType)(0),        // 0: reckon.gateway.v1.StoreEventType
	(StoreMode)(0),             // 1: reckon.gateway.v1.StoreMode
	(*ListStoresRequest)(nil),  // 2: reckon.gateway.v1.ListStoresRequest
	(*ListStoresResponse)(nil), // 3: reckon.gateway.v1.ListStoresResponse
	(*GetStoreRequest)(nil),    // 4: reckon.gateway.v1.GetStoreRequest
	(*GetStoreResponse)(nil),   // 5: reckon.gateway.v1.GetStoreResponse
	(*WatchStoresRequest)(nil), // 6: reckon.gateway.v1.WatchStoresRequest
	(*StoreEvent)(nil),         // 7: reckon.gateway.v1.StoreEvent
	(*StoreInstance)(nil),      // 8: reckon.gateway.v1.StoreInstance
}
var file_reckon_stores_proto_depIdxs = []int32{
	8, // 0: reckon.gateway.v1.ListStoresResponse.instances:type_name -> reckon.gateway.v1.StoreInstance
	8, // 1: reckon.gateway.v1.GetStoreResponse.instances:type_name -> reckon.gateway.v1.StoreInstance
	0, // 2: reckon.gateway.v1.StoreEvent.type:type_name -> reckon.gateway.v1.StoreEventType
	8, // 3: reckon.gateway.v1.StoreEvent.instance:type_name -> reckon.gateway.v1.StoreInstance
	1, // 4: reckon.gateway.v1.StoreInstance.mode:type_name -> reckon.gateway.v1.StoreMode
	2, // 5: reckon.gateway.v1.StoresService.ListStores:input_type -> reckon.gateway.v1.ListStoresRequest
	4, // 6: reckon.gateway.v1.StoresService.GetStore:input_type -> reckon.gateway.v1.GetStoreRequest
	6, // 7: reckon.gateway.v1.StoresService.WatchStores:input_type -> reckon.gateway.v1.WatchStoresRequest
	3, // 8: reckon.gateway.v1.StoresService.ListStores:output_type -> reckon.gateway.v1.ListStoresResponse
	5, // 9: reckon.gateway.v1.StoresService.GetStore:output_type -> reckon.gateway.v1.GetStoreResponse
	7, // 10: reckon.gateway.v1.StoresService.WatchStores:output_type -> reckon.gateway.v1.StoreEvent
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_reckon_stores_proto_init() }
func file_reckon_stores_proto_init() {
	if File_reckon_stores_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_stores_proto_rawDesc), len(file_reckon_stores_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_stores_proto_goTypes,
		DependencyIndexes: file_reckon_stores_proto_depIdxs,
		EnumInfos:         file_reckon_stores_proto_enumTypes,
		MessageInfos:      file_reckon_stores_proto_msgTypes,
	}.Build()
	File_reckon_stores_proto = out.File
	file_reckon_stores_proto_goTypes = nil
	file_reckon_stores_proto_depIdxs = nil
}
