// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_causation.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CausationService_GetEffects_FullMethodName          = "/reckon.gateway.v1.CausationService/GetEffects"
	CausationService_GetCause_FullMethodName            = "/reckon.gateway.v1.CausationService/GetCause"
	CausationService_GetCausationChain_FullMethodName   = "/reckon.gateway.v1.CausationService/GetCausationChain"
	CausationService_GetCorrelated_FullMethodName       = "/reckon.gateway.v1.CausationService/GetCorrelated"
	CausationService_BuildCausationGraph_FullMethodName = "/reckon.gateway.v1.CausationService/BuildCausationGraph"
)

// CausationServiceClient is the client API for CausationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CausationService provides causation and correlation tracking.
//
// Track event lineage: which event caused which, and which events
// share the same business correlation.
type CausationServiceClient interface {
	// Get all events caused by a specific event.
	GetEffects(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationResponse, error)
	// Get the event that caused a specific event.
	GetCause(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*SingleEventResponse, error)
	// Get the full causation chain from root to the given event.
	GetCausationChain(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationResponse, error)
	// Get all events sharing the same correlation_id.
	GetCorrelated(ctx context.Context, in *CorrelationRequest, opts ...grpc.CallOption) (*CausationResponse, error)
	// Build a causation graph (tree of cause→effect relationships).
	BuildCausationGraph(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationGraphResponse, error)
}

type causationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCausationServiceClient(cc grpc.ClientConnInterface) CausationServiceClient {
	return &causationServiceClient{cc}
}

func (c *causationServiceClient) GetEffects(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CausationResponse)
	err := c.cc.Invoke(ctx, CausationService_GetEffects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationServiceClient) GetCause(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*SingleEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingleEventResponse)
	err := c.cc.Invoke(ctx, CausationService_GetCause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationServiceClient) GetCausationChain(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CausationResponse)
	err := c.cc.Invoke(ctx, CausationService_GetCausationChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationServiceClient) GetCorrelated(ctx context.Context, in *CorrelationRequest, opts ...grpc.CallOption) (*CausationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CausationResponse)
	err := c.cc.Invoke(ctx, CausationService_GetCorrelated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *causationServiceClient) BuildCausationGraph(ctx context.Context, in *CausationRequest, opts ...grpc.CallOption) (*CausationGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CausationGraphResponse)
	err := c.cc.Invoke(ctx, CausationService_BuildCausationGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CausationServiceServer is the server API for CausationService service.
// All implementations should embed UnimplementedCausationServiceServer
// for forward compatibility.
//
// CausationService provides causation and correlation tracking.
//
// Track event lineage: which event caused which, and which events
// share the same business correlation.
type CausationServiceServer interface {
	// Get all events caused by a specific event.
	GetEffects(context.Context, *CausationRequest) (*CausationResponse, error)
	// Get the event that caused a specific event.
	GetCause(context.Context, *CausationRequest) (*SingleEventResponse, error)
	// Get the full causation chain from root to the given event.
	GetCausationChain(context.Context, *CausationRequest) (*CausationResponse, error)
	// Get all events sharing the same correlation_id.
	GetCorrelated(context.Context, *CorrelationRequest) (*CausationResponse, error)
	// Build a causation graph (tree of cause→effect relationships).
	BuildCausationGraph(context.Context, *CausationRequest) (*CausationGraphResponse, error)
}

// UnimplementedCausationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCausationServiceServer struct{}

func (UnimplementedCausationServiceServer) GetEffects(context.Context, *CausationRequest) (*CausationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEffects not implemented")
}
func (UnimplementedCausationServiceServer) GetCause(context.Context, *CausationRequest) (*SingleEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCause not implemented")
}
func (UnimplementedCausationServiceServer) GetCausationChain(context.Context, *CausationRequest) (*CausationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCausationChain not implemented")
}
func (UnimplementedCausationServiceServer) GetCorrelated(context.Context, *CorrelationRequest) (*CausationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCorrelated not implemented")
}
func (UnimplementedCausationServiceServer) BuildCausationGraph(context.Context, *CausationRequest) (*CausationGraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildCausationGraph not implemented")
}
func (UnimplementedCausationServiceServer) testEmbeddedByValue() {}

// UnsafeCausationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CausationServiceServer will
// result in compilation errors.
type UnsafeCausationServiceServer interface {
	mustEmbedUnimplementedCausationServiceServer()
}

func RegisterCausationServiceServer(s grpc.ServiceRegistrar, srv CausationServiceServer) {
	// If the following call panics, it indicates UnimplementedCausationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CausationService_ServiceDesc, srv)
}

func _CausationService_GetEffects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CausationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationServiceServer).GetEffects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationService_GetEffects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationServiceServer).GetEffects(ctx, req.(*CausationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationService_GetCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CausationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationServiceServer).GetCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationService_GetCause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationServiceServer).GetCause(ctx, req.(*CausationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationService_GetCausationChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CausationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationServiceServer).GetCausationChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationService_GetCausationChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationServiceServer).GetCausationChain(ctx, req.(*CausationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationService_GetCorrelated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationServiceServer).GetCorrelated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationService_GetCorrelated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationServiceServer).GetCorrelated(ctx, req.(*CorrelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CausationService_BuildCausationGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CausationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausationServiceServer).BuildCausationGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CausationService_BuildCausationGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausationServiceServer).BuildCausationGraph(ctx, req.(*CausationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CausationService_ServiceDesc is the grpc.ServiceDesc for CausationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CausationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.CausationService",
	HandlerType: (*CausationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEffects",
			Handler:    _CausationService_GetEffects_Handler,
		},
		{
			MethodName: "GetCause",
			Handler:    _CausationService_GetCause_Handler,
		},
		{
			MethodName: "GetCausationChain",
			Handler:    _CausationService_GetCausationChain_Handler,
		},
		{
			MethodName: "GetCorrelated",
			Handler:    _CausationService_GetCorrelated_Handler,
		},
		{
			MethodName: "BuildCausationGraph",
			Handler:    _CausationService_BuildCausationGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reckon_causation.proto",
}
