// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_streams.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_AppendEvents_FullMethodName        = "/reckon.gateway.v1.StreamService/AppendEvents"
	StreamService_ReadStreamForward_FullMethodName   = "/reckon.gateway.v1.StreamService/ReadStreamForward"
	StreamService_ReadStreamBackward_FullMethodName  = "/reckon.gateway.v1.StreamService/ReadStreamBackward"
	StreamService_StreamEventsForward_FullMethodName = "/reckon.gateway.v1.StreamService/StreamEventsForward"
	StreamService_GetStreamVersion_FullMethodName    = "/reckon.gateway.v1.StreamService/GetStreamVersion"
	StreamService_ListStreams_FullMethodName         = "/reckon.gateway.v1.StreamService/ListStreams"
	StreamService_DeleteStream_FullMethodName        = "/reckon.gateway.v1.StreamService/DeleteStream"
	StreamService_ReadByEventTypes_FullMethodName    = "/reckon.gateway.v1.StreamService/ReadByEventTypes"
	StreamService_ReadByTags_FullMethodName          = "/reckon.gateway.v1.StreamService/ReadByTags"
	StreamService_ReadAllGlobal_FullMethodName       = "/reckon.gateway.v1.StreamService/ReadAllGlobal"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamService provides event stream operations for the ReckonDB event store.
//
// Streams are append-only sequences of events identified by a stream_id.
// Each event has a monotonically increasing version within its stream.
type StreamServiceClient interface {
	// Append events to a stream with optional optimistic concurrency control.
	AppendEvents(ctx context.Context, in *AppendEventsRequest, opts ...grpc.CallOption) (*AppendEventsResponse, error)
	// Read events from a stream in forward direction.
	ReadStreamForward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
	// Read events from a stream in backward direction.
	ReadStreamBackward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
	// Stream events forward in real-time (server-streaming).
	StreamEventsForward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordedEvent], error)
	// Get the current version (last event number) of a stream.
	GetStreamVersion(ctx context.Context, in *GetStreamVersionRequest, opts ...grpc.CallOption) (*GetStreamVersionResponse, error)
	// List all streams in the store.
	ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	// Delete a stream.
	DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error)
	// Read events by event types across all streams.
	ReadByEventTypes(ctx context.Context, in *ReadByEventTypesRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
	// Read events by tags across all streams.
	ReadByTags(ctx context.Context, in *ReadByTagsRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
	// Read all events globally, ordered by epoch_us.
	ReadAllGlobal(ctx context.Context, in *ReadAllGlobalRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) AppendEvents(ctx context.Context, in *AppendEventsRequest, opts ...grpc.CallOption) (*AppendEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEventsResponse)
	err := c.cc.Invoke(ctx, StreamService_AppendEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ReadStreamForward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ReadStreamForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ReadStreamBackward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ReadStreamBackward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) StreamEventsForward(ctx context.Context, in *ReadStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RecordedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_StreamEventsForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStreamRequest, RecordedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamEventsForwardClient = grpc.ServerStreamingClient[RecordedEvent]

func (c *streamServiceClient) GetStreamVersion(ctx context.Context, in *GetStreamVersionRequest, opts ...grpc.CallOption) (*GetStreamVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamVersionResponse)
	err := c.cc.Invoke(ctx, StreamService_GetStreamVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, StreamService_ListStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) DeleteStream(ctx context.Context, in *DeleteStreamRequest, opts ...grpc.CallOption) (*DeleteStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_DeleteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ReadByEventTypes(ctx context.Context, in *ReadByEventTypesRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ReadByEventTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ReadByTags(ctx context.Context, in *ReadByTagsRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ReadByTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) ReadAllGlobal(ctx context.Context, in *ReadAllGlobalRequest, opts ...grpc.CallOption) (*ReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadStreamResponse)
	err := c.cc.Invoke(ctx, StreamService_ReadAllGlobal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations should embed UnimplementedStreamServiceServer
// for forward compatibility.
//
// StreamService provides event stream operations for the ReckonDB event store.
//
// Streams are append-only sequences of events identified by a stream_id.
// Each event has a monotonically increasing version within its stream.
type StreamServiceServer interface {
	// Append events to a stream with optional optimistic concurrency control.
	AppendEvents(context.Context, *AppendEventsRequest) (*AppendEventsResponse, error)
	// Read events from a stream in forward direction.
	ReadStreamForward(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	// Read events from a stream in backward direction.
	ReadStreamBackward(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error)
	// Stream events forward in real-time (server-streaming).
	StreamEventsForward(*ReadStreamRequest, grpc.ServerStreamingServer[RecordedEvent]) error
	// Get the current version (last event number) of a stream.
	GetStreamVersion(context.Context, *GetStreamVersionRequest) (*GetStreamVersionResponse, error)
	// List all streams in the store.
	ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error)
	// Delete a stream.
	DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamResponse, error)
	// Read events by event types across all streams.
	ReadByEventTypes(context.Context, *ReadByEventTypesRequest) (*ReadStreamResponse, error)
	// Read events by tags across all streams.
	ReadByTags(context.Context, *ReadByTagsRequest) (*ReadStreamResponse, error)
	// Read all events globally, ordered by epoch_us.
	ReadAllGlobal(context.Context, *ReadAllGlobalRequest) (*ReadStreamResponse, error)
}

// UnimplementedStreamServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) AppendEvents(context.Context, *AppendEventsRequest) (*AppendEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEvents not implemented")
}
func (UnimplementedStreamServiceServer) ReadStreamForward(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadStreamForward not implemented")
}
func (UnimplementedStreamServiceServer) ReadStreamBackward(context.Context, *ReadStreamRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadStreamBackward not implemented")
}
func (UnimplementedStreamServiceServer) StreamEventsForward(*ReadStreamRequest, grpc.ServerStreamingServer[RecordedEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEventsForward not implemented")
}
func (UnimplementedStreamServiceServer) GetStreamVersion(context.Context, *GetStreamVersionRequest) (*GetStreamVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamVersion not implemented")
}
func (UnimplementedStreamServiceServer) ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedStreamServiceServer) DeleteStream(context.Context, *DeleteStreamRequest) (*DeleteStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStream not implemented")
}
func (UnimplementedStreamServiceServer) ReadByEventTypes(context.Context, *ReadByEventTypesRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadByEventTypes not implemented")
}
func (UnimplementedStreamServiceServer) ReadByTags(context.Context, *ReadByTagsRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadByTags not implemented")
}
func (UnimplementedStreamServiceServer) ReadAllGlobal(context.Context, *ReadAllGlobalRequest) (*ReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllGlobal not implemented")
}
func (UnimplementedStreamServiceServer) testEmbeddedByValue() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_AppendEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).AppendEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_AppendEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).AppendEvents(ctx, req.(*AppendEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ReadStreamForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ReadStreamForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ReadStreamForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ReadStreamForward(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ReadStreamBackward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ReadStreamBackward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ReadStreamBackward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ReadStreamBackward(ctx, req.(*ReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_StreamEventsForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamEventsForward(m, &grpc.GenericServerStream[ReadStreamRequest, RecordedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamEventsForwardServer = grpc.ServerStreamingServer[RecordedEvent]

func _StreamService_GetStreamVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetStreamVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_GetStreamVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetStreamVersion(ctx, req.(*GetStreamVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ListStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ListStreams(ctx, req.(*ListStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_DeleteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).DeleteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_DeleteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).DeleteStream(ctx, req.(*DeleteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ReadByEventTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByEventTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ReadByEventTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ReadByEventTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ReadByEventTypes(ctx, req.(*ReadByEventTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ReadByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadByTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ReadByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ReadByTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ReadByTags(ctx, req.(*ReadByTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_ReadAllGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).ReadAllGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamService_ReadAllGlobal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).ReadAllGlobal(ctx, req.(*ReadAllGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEvents",
			Handler:    _StreamService_AppendEvents_Handler,
		},
		{
			MethodName: "ReadStreamForward",
			Handler:    _StreamService_ReadStreamForward_Handler,
		},
		{
			MethodName: "ReadStreamBackward",
			Handler:    _StreamService_ReadStreamBackward_Handler,
		},
		{
			MethodName: "GetStreamVersion",
			Handler:    _StreamService_GetStreamVersion_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _StreamService_ListStreams_Handler,
		},
		{
			MethodName: "DeleteStream",
			Handler:    _StreamService_DeleteStream_Handler,
		},
		{
			MethodName: "ReadByEventTypes",
			Handler:    _StreamService_ReadByEventTypes_Handler,
		},
		{
			MethodName: "ReadByTags",
			Handler:    _StreamService_ReadByTags_Handler,
		},
		{
			MethodName: "ReadAllGlobal",
			Handler:    _StreamService_ReadAllGlobal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEventsForward",
			Handler:       _StreamService_StreamEventsForward_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reckon_streams.proto",
}
