// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reckon_schema.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Schema        []byte                 `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaRequest) Reset() {
	*x = RegisterSchemaRequest{}
	mi := &file_reckon_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaRequest) ProtoMessage() {}

func (x *RegisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*RegisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSchemaRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *RegisterSchemaRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RegisterSchemaRequest) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type UnregisterSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterSchemaRequest) Reset() {
	*x = UnregisterSchemaRequest{}
	mi := &file_reckon_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterSchemaRequest) ProtoMessage() {}

func (x *UnregisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*UnregisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{1}
}

func (x *UnregisterSchemaRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *UnregisterSchemaRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_reckon_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchemaRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetSchemaRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ListSchemasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasRequest) Reset() {
	*x = ListSchemasRequest{}
	mi := &file_reckon_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasRequest) ProtoMessage() {}

func (x *ListSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasRequest.ProtoReflect.Descriptor instead.
func (*ListSchemasRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{3}
}

func (x *ListSchemasRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetSchemaVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaVersionRequest) Reset() {
	*x = GetSchemaVersionRequest{}
	mi := &file_reckon_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaVersionRequest) ProtoMessage() {}

func (x *GetSchemaVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaVersionRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaVersionRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchemaVersionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetSchemaVersionRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type UpcastEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Events        []*RecordedEvent       `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcastEventsRequest) Reset() {
	*x = UpcastEventsRequest{}
	mi := &file_reckon_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcastEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcastEventsRequest) ProtoMessage() {}

func (x *UpcastEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcastEventsRequest.ProtoReflect.Descriptor instead.
func (*UpcastEventsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{5}
}

func (x *UpcastEventsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *UpcastEventsRequest) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RegisterSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	mi := &file_reckon_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{6}
}

type UnregisterSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterSchemaResponse) Reset() {
	*x = UnregisterSchemaResponse{}
	mi := &file_reckon_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterSchemaResponse) ProtoMessage() {}

func (x *UnregisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*UnregisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{7}
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Schema        []byte                 `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_reckon_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{8}
}

func (x *GetSchemaResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GetSchemaResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetSchemaResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListSchemasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schemas       []*GetSchemaResponse   `protobuf:"bytes,1,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchemasResponse) Reset() {
	*x = ListSchemasResponse{}
	mi := &file_reckon_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchemasResponse) ProtoMessage() {}

func (x *ListSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchemasResponse.ProtoReflect.Descriptor instead.
func (*ListSchemasResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{9}
}

func (x *ListSchemasResponse) GetSchemas() []*GetSchemaResponse {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type GetSchemaVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaVersionResponse) Reset() {
	*x = GetSchemaVersionResponse{}
	mi := &file_reckon_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaVersionResponse) ProtoMessage() {}

func (x *GetSchemaVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaVersionResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaVersionResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{10}
}

func (x *GetSchemaVersionResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpcastEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RecordedEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpcastEventsResponse) Reset() {
	*x = UpcastEventsResponse{}
	mi := &file_reckon_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpcastEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpcastEventsResponse) ProtoMessage() {}

func (x *UpcastEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpcastEventsResponse.ProtoReflect.Descriptor instead.
func (*UpcastEventsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_schema_proto_rawDescGZIP(), []int{11}
}

func (x *UpcastEventsResponse) GetEvents() []*RecordedEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_reckon_schema_proto protoreflect.FileDescriptor

const file_reckon_schema_proto_rawDesc = "" +
	"\n" +
	"\x13reckon_schema.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"i\n" +
	"\x15RegisterSchemaRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06schema\x18\x03 \x01(\fR\x06schema\"S\n" +
	"\x17UnregisterSchemaRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\"L\n" +
	"\x10GetSchemaRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\"/\n" +
	"\x12ListSchemasRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"S\n" +
	"\x17GetSchemaVersionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\"j\n" +
	"\x13UpcastEventsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x128\n" +
	"\x06events\x18\x02 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events\"\x18\n" +
	"\x16RegisterSchemaResponse\"\x1a\n" +
	"\x18UnregisterSchemaResponse\"d\n" +
	"\x11GetSchemaResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\fR\x06schema\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"U\n" +
	"\x13ListSchemasResponse\x12>\n" +
	"\aschemas\x18\x01 \x03(\v2$.reckon.gateway.v1.GetSchemaResponseR\aschemas\"4\n" +
	"\x18GetSchemaVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\"P\n" +
	"\x14UpcastEventsResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .reckon.gateway.v1.RecordedEventR\x06events2\xe7\x04\n" +
	"\rSchemaService\x12e\n" +
	"\x0eRegisterSchema\x12(.reckon.gateway.v1.RegisterSchemaRequest\x1a).reckon.gateway.v1.RegisterSchemaResponse\x12k\n" +
	"\x10UnregisterSchema\x12*.reckon.gateway.v1.UnregisterSchemaRequest\x1a+.reckon.gateway.v1.UnregisterSchemaResponse\x12V\n" +
	"\tGetSchema\x12#.reckon.gateway.v1.GetSchemaRequest\x1a$.reckon.gateway.v1.GetSchemaResponse\x12\\\n" +
	"\vListSchemas\x12%.reckon.gateway.v1.ListSchemasRequest\x1a&.reckon.gateway.v1.ListSchemasResponse\x12k\n" +
	"\x10GetSchemaVersion\x12*.reckon.gateway.v1.GetSchemaVersionRequest\x1a+.reckon.gateway.v1.GetSchemaVersionResponse\x12_\n" +
	"\fUpcastEvents\x12&.reckon.gateway.v1.UpcastEventsRequest\x1a'.reckon.gateway.v1.UpcastEventsResponseBCZAcodeberg.org/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_schema_proto_rawDescOnce sync.Once
	file_reckon_schema_proto_rawDescData []byte
)

func file_reckon_schema_proto_rawDescGZIP() []byte {
	file_reckon_schema_proto_rawDescOnce.Do(func() {
		file_reckon_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_schema_proto_rawDesc), len(file_reckon_schema_proto_rawDesc)))
	})
	return file_reckon_schema_proto_rawDescData
}

var file_reckon_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_reckon_schema_proto_goTypes = []any{
	(*RegisterSchemaRequest)(nil),    // 0: reckon.gateway.v1.RegisterSchemaRequest
	(*UnregisterSchemaRequest)(nil),  // 1: reckon.gateway.v1.UnregisterSchemaRequest
	(*GetSchemaRequest)(nil),         // 2: reckon.gateway.v1.GetSchemaRequest
	(*ListSchemasRequest)(nil),       // 3: reckon.gateway.v1.ListSchemasRequest
	(*GetSchemaVersionRequest)(nil),  // 4: reckon.gateway.v1.GetSchemaVersionRequest
	(*UpcastEventsRequest)(nil),      // 5: reckon.gateway.v1.UpcastEventsRequest
	(*RegisterSchemaResponse)(nil),   // 6: reckon.gateway.v1.RegisterSchemaResponse
	(*UnregisterSchemaResponse)(nil), // 7: reckon.gateway.v1.UnregisterSchemaResponse
	(*GetSchemaResponse)(nil),        // 8: reckon.gateway.v1.GetSchemaResponse
	(*ListSchemasResponse)(nil),      // 9: reckon.gateway.v1.ListSchemasResponse
	(*GetSchemaVersionResponse)(nil), // 10: reckon.gateway.v1.GetSchemaVersionResponse
	(*UpcastEventsResponse)(nil),     // 11: reckon.gateway.v1.UpcastEventsResponse
	(*RecordedEvent)(nil),            // 12: reckon.gateway.v1.RecordedEvent
}
var file_reckon_schema_proto_depIdxs = []int32{
	12, // 0: reckon.gateway.v1.UpcastEventsRequest.events:type_name -> reckon.gateway.v1.RecordedEvent
	8,  // 1: reckon.gateway.v1.ListSchemasResponse.schemas:type_name -> reckon.gateway.v1.GetSchemaResponse
	12, // 2: reckon.gateway.v1.UpcastEventsResponse.events:type_name -> reckon.gateway.v1.RecordedEvent
	0,  // 3: reckon.gateway.v1.SchemaService.RegisterSchema:input_type -> reckon.gateway.v1.RegisterSchemaRequest
	1,  // 4: reckon.gateway.v1.SchemaService.UnregisterSchema:input_type -> reckon.gateway.v1.UnregisterSchemaRequest
	2,  // 5: reckon.gateway.v1.SchemaService.GetSchema:input_type -> reckon.gateway.v1.GetSchemaRequest
	3,  // 6: reckon.gateway.v1.SchemaService.ListSchemas:input_type -> reckon.gateway.v1.ListSchemasRequest
	4,  // 7: reckon.gateway.v1.SchemaService.GetSchemaVersion:input_type -> reckon.gateway.v1.GetSchemaVersionRequest
	5,  // 8: reckon.gateway.v1.SchemaService.UpcastEvents:input_type -> reckon.gateway.v1.UpcastEventsRequest
	6,  // 9: reckon.gateway.v1.SchemaService.RegisterSchema:output_type -> reckon.gateway.v1.RegisterSchemaResponse
	7,  // 10: reckon.gateway.v1.SchemaService.UnregisterSchema:output_type -> reckon.gateway.v1.UnregisterSchemaResponse
	8,  // 11: reckon.gateway.v1.SchemaService.GetSchema:output_type -> reckon.gateway.v1.GetSchemaResponse
	9,  // 12: reckon.gateway.v1.SchemaService.ListSchemas:output_type -> reckon.gateway.v1.ListSchemasResponse
	10, // 13: reckon.gateway.v1.SchemaService.GetSchemaVersion:output_type -> reckon.gateway.v1.GetSchemaVersionResponse
	11, // 14: reckon.gateway.v1.SchemaService.UpcastEvents:output_type -> reckon.gateway.v1.UpcastEventsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_reckon_schema_proto_init() }
func file_reckon_schema_proto_init() {
	if File_reckon_schema_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_schema_proto_rawDesc), len(file_reckon_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_schema_proto_goTypes,
		DependencyIndexes: file_reckon_schema_proto_depIdxs,
		MessageInfos:      file_reckon_schema_proto_msgTypes,
	}.Build()
	File_reckon_schema_proto = out.File
	file_reckon_schema_proto_goTypes = nil
	file_reckon_schema_proto_depIdxs = nil
}
