// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_admin.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_GetStoreStats_FullMethodName       = "/reckon.gateway.v1.AdminService/GetStoreStats"
	AdminService_GetStreamInfo_FullMethodName       = "/reckon.gateway.v1.AdminService/GetStreamInfo"
	AdminService_GetEventTypeSummary_FullMethodName = "/reckon.gateway.v1.AdminService/GetEventTypeSummary"
	AdminService_Scavenge_FullMethodName            = "/reckon.gateway.v1.AdminService/Scavenge"
	AdminService_ScavengeMatching_FullMethodName    = "/reckon.gateway.v1.AdminService/ScavengeMatching"
	AdminService_ScavengeDryRun_FullMethodName      = "/reckon.gateway.v1.AdminService/ScavengeDryRun"
	AdminService_CreateLink_FullMethodName          = "/reckon.gateway.v1.AdminService/CreateLink"
	AdminService_DeleteLink_FullMethodName          = "/reckon.gateway.v1.AdminService/DeleteLink"
	AdminService_GetLink_FullMethodName             = "/reckon.gateway.v1.AdminService/GetLink"
	AdminService_ListLinks_FullMethodName           = "/reckon.gateway.v1.AdminService/ListLinks"
	AdminService_StartLink_FullMethodName           = "/reckon.gateway.v1.AdminService/StartLink"
	AdminService_StopLink_FullMethodName            = "/reckon.gateway.v1.AdminService/StopLink"
	AdminService_GetLinkInfo_FullMethodName         = "/reckon.gateway.v1.AdminService/GetLinkInfo"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService provides store inspection, scavenging, and link management.
type AdminServiceClient interface {
	// Get overall store statistics.
	GetStoreStats(ctx context.Context, in *StoreStatsRequest, opts ...grpc.CallOption) (*StoreStatsResponse, error)
	// Get detailed information about a specific stream.
	GetStreamInfo(ctx context.Context, in *StreamInfoRequest, opts ...grpc.CallOption) (*StreamInfoResponse, error)
	// Get a summary of event types and their counts.
	GetEventTypeSummary(ctx context.Context, in *EventTypeSummaryRequest, opts ...grpc.CallOption) (*EventTypeSummaryResponse, error)
	// Scavenge (compact) a stream by removing superseded events.
	Scavenge(ctx context.Context, in *ScavengeRequest, opts ...grpc.CallOption) (*ScavengeResponse, error)
	// Scavenge all streams matching a pattern.
	ScavengeMatching(ctx context.Context, in *ScavengeMatchingRequest, opts ...grpc.CallOption) (*ScavengeMatchingResponse, error)
	// Preview what a scavenge operation would do (dry run).
	ScavengeDryRun(ctx context.Context, in *ScavengeRequest, opts ...grpc.CallOption) (*ScavengeResponse, error)
	// Create a link between streams.
	CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error)
	// Delete a link.
	DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error)
	// Get link information.
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*LinkInfo, error)
	// List all links for a store.
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	// Start a link (begin processing).
	StartLink(ctx context.Context, in *StartLinkRequest, opts ...grpc.CallOption) (*StartLinkResponse, error)
	// Stop a link (pause processing).
	StopLink(ctx context.Context, in *StopLinkRequest, opts ...grpc.CallOption) (*StopLinkResponse, error)
	// Get runtime info about a link.
	GetLinkInfo(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*LinkRuntimeInfo, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetStoreStats(ctx context.Context, in *StoreStatsRequest, opts ...grpc.CallOption) (*StoreStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetStoreStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStreamInfo(ctx context.Context, in *StreamInfoRequest, opts ...grpc.CallOption) (*StreamInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetStreamInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetEventTypeSummary(ctx context.Context, in *EventTypeSummaryRequest, opts ...grpc.CallOption) (*EventTypeSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventTypeSummaryResponse)
	err := c.cc.Invoke(ctx, AdminService_GetEventTypeSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Scavenge(ctx context.Context, in *ScavengeRequest, opts ...grpc.CallOption) (*ScavengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScavengeResponse)
	err := c.cc.Invoke(ctx, AdminService_Scavenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ScavengeMatching(ctx context.Context, in *ScavengeMatchingRequest, opts ...grpc.CallOption) (*ScavengeMatchingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScavengeMatchingResponse)
	err := c.cc.Invoke(ctx, AdminService_ScavengeMatching_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ScavengeDryRun(ctx context.Context, in *ScavengeRequest, opts ...grpc.CallOption) (*ScavengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScavengeResponse)
	err := c.cc.Invoke(ctx, AdminService_ScavengeDryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateLink(ctx context.Context, in *CreateLinkRequest, opts ...grpc.CallOption) (*CreateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLinkResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*DeleteLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLinkResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*LinkInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkInfo)
	err := c.cc.Invoke(ctx, AdminService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, AdminService_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartLink(ctx context.Context, in *StartLinkRequest, opts ...grpc.CallOption) (*StartLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLinkResponse)
	err := c.cc.Invoke(ctx, AdminService_StartLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopLink(ctx context.Context, in *StopLinkRequest, opts ...grpc.CallOption) (*StopLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopLinkResponse)
	err := c.cc.Invoke(ctx, AdminService_StopLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetLinkInfo(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*LinkRuntimeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkRuntimeInfo)
	err := c.cc.Invoke(ctx, AdminService_GetLinkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations should embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService provides store inspection, scavenging, and link management.
type AdminServiceServer interface {
	// Get overall store statistics.
	GetStoreStats(context.Context, *StoreStatsRequest) (*StoreStatsResponse, error)
	// Get detailed information about a specific stream.
	GetStreamInfo(context.Context, *StreamInfoRequest) (*StreamInfoResponse, error)
	// Get a summary of event types and their counts.
	GetEventTypeSummary(context.Context, *EventTypeSummaryRequest) (*EventTypeSummaryResponse, error)
	// Scavenge (compact) a stream by removing superseded events.
	Scavenge(context.Context, *ScavengeRequest) (*ScavengeResponse, error)
	// Scavenge all streams matching a pattern.
	ScavengeMatching(context.Context, *ScavengeMatchingRequest) (*ScavengeMatchingResponse, error)
	// Preview what a scavenge operation would do (dry run).
	ScavengeDryRun(context.Context, *ScavengeRequest) (*ScavengeResponse, error)
	// Create a link between streams.
	CreateLink(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error)
	// Delete a link.
	DeleteLink(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error)
	// Get link information.
	GetLink(context.Context, *GetLinkRequest) (*LinkInfo, error)
	// List all links for a store.
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	// Start a link (begin processing).
	StartLink(context.Context, *StartLinkRequest) (*StartLinkResponse, error)
	// Stop a link (pause processing).
	StopLink(context.Context, *StopLinkRequest) (*StopLinkResponse, error)
	// Get runtime info about a link.
	GetLinkInfo(context.Context, *GetLinkRequest) (*LinkRuntimeInfo, error)
}

// UnimplementedAdminServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetStoreStats(context.Context, *StoreStatsRequest) (*StoreStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreStats not implemented")
}
func (UnimplementedAdminServiceServer) GetStreamInfo(context.Context, *StreamInfoRequest) (*StreamInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamInfo not implemented")
}
func (UnimplementedAdminServiceServer) GetEventTypeSummary(context.Context, *EventTypeSummaryRequest) (*EventTypeSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventTypeSummary not implemented")
}
func (UnimplementedAdminServiceServer) Scavenge(context.Context, *ScavengeRequest) (*ScavengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scavenge not implemented")
}
func (UnimplementedAdminServiceServer) ScavengeMatching(context.Context, *ScavengeMatchingRequest) (*ScavengeMatchingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScavengeMatching not implemented")
}
func (UnimplementedAdminServiceServer) ScavengeDryRun(context.Context, *ScavengeRequest) (*ScavengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScavengeDryRun not implemented")
}
func (UnimplementedAdminServiceServer) CreateLink(context.Context, *CreateLinkRequest) (*CreateLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedAdminServiceServer) DeleteLink(context.Context, *DeleteLinkRequest) (*DeleteLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedAdminServiceServer) GetLink(context.Context, *GetLinkRequest) (*LinkInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedAdminServiceServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedAdminServiceServer) StartLink(context.Context, *StartLinkRequest) (*StartLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartLink not implemented")
}
func (UnimplementedAdminServiceServer) StopLink(context.Context, *StopLinkRequest) (*StopLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopLink not implemented")
}
func (UnimplementedAdminServiceServer) GetLinkInfo(context.Context, *GetLinkRequest) (*LinkRuntimeInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLinkInfo not implemented")
}
func (UnimplementedAdminServiceServer) testEmbeddedByValue() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetStoreStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStoreStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStoreStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStoreStats(ctx, req.(*StoreStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStreamInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStreamInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStreamInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStreamInfo(ctx, req.(*StreamInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetEventTypeSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventTypeSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetEventTypeSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetEventTypeSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetEventTypeSummary(ctx, req.(*EventTypeSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Scavenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScavengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Scavenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_Scavenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Scavenge(ctx, req.(*ScavengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ScavengeMatching_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScavengeMatchingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ScavengeMatching(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ScavengeMatching_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ScavengeMatching(ctx, req.(*ScavengeMatchingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ScavengeDryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScavengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ScavengeDryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ScavengeDryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ScavengeDryRun(ctx, req.(*ScavengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateLink(ctx, req.(*CreateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteLink(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StartLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartLink(ctx, req.(*StartLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StopLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopLink(ctx, req.(*StopLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetLinkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetLinkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetLinkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetLinkInfo(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStoreStats",
			Handler:    _AdminService_GetStoreStats_Handler,
		},
		{
			MethodName: "GetStreamInfo",
			Handler:    _AdminService_GetStreamInfo_Handler,
		},
		{
			MethodName: "GetEventTypeSummary",
			Handler:    _AdminService_GetEventTypeSummary_Handler,
		},
		{
			MethodName: "Scavenge",
			Handler:    _AdminService_Scavenge_Handler,
		},
		{
			MethodName: "ScavengeMatching",
			Handler:    _AdminService_ScavengeMatching_Handler,
		},
		{
			MethodName: "ScavengeDryRun",
			Handler:    _AdminService_ScavengeDryRun_Handler,
		},
		{
			MethodName: "CreateLink",
			Handler:    _AdminService_CreateLink_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _AdminService_DeleteLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _AdminService_GetLink_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _AdminService_ListLinks_Handler,
		},
		{
			MethodName: "StartLink",
			Handler:    _AdminService_StartLink_Handler,
		},
		{
			MethodName: "StopLink",
			Handler:    _AdminService_StopLink_Handler,
		},
		{
			MethodName: "GetLinkInfo",
			Handler:    _AdminService_GetLinkInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reckon_admin.proto",
}
