// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_dcb.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DcbService_AppendIfNoTagMatches_FullMethodName = "/reckon.gateway.v1.DcbService/AppendIfNoTagMatches"
	DcbService_ReadDcbContext_FullMethodName       = "/reckon.gateway.v1.DcbService/ReadDcbContext"
)

// DcbServiceClient is the client API for DcbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DcbService exposes the Dynamic Consistency Boundary (DCB) primitive
// of ReckonDB to polyglot clients.
//
// Where the existing StreamService.AppendEvents enforces consistency
// against a per-stream version counter (the classic event-sourcing
// optimistic concurrency model), DCB enforces consistency against a
// tag-filter context query: "no event matching this filter has been
// written since I last looked".
//
// The pattern is the cross-cutting complement to per-aggregate
// consistency. Use it when the invariant a write must preserve
// crosses streams (uniqueness, allocation, rate-limit, eligibility)
// rather than lives inside one aggregate.
//
// Requires backing ReckonDB cluster on reckon-db 3.1.1+
// (reckon_gater 2.3.1+). Older backings surface UNIMPLEMENTED.
type DcbServiceClient interface {
	// Conditionally append events under the DCB pseudo-stream.
	//
	// Server evaluates the TagFilter against the tag index. If any
	// event matching the filter has seq strictly greater than the
	// supplied seq_cutoff, the write is rejected with a Conflict
	// response carrying the highest matching seq the server observed.
	// Otherwise the events are appended atomically and Committed
	// carries the last assigned seq.
	//
	// seq_cutoff is signed: -1 means "I have seen nothing yet" and
	// ANY matching event is a conflict. A value of N (>= 0) means
	// "I saw through seq N" and only seqs strictly above N conflict.
	//
	// The conditional-append is atomic across the Ra log entry: the
	// server either commits all events or none. Partial commits do
	// not happen.
	AppendIfNoTagMatches(ctx context.Context, in *AppendIfNoTagMatchesRequest, opts ...grpc.CallOption) (*AppendIfNoTagMatchesResponse, error)
	// Read events from the DCB pseudo-stream that match a TagFilter,
	// ordered by seq ascending. Use this to populate the "context"
	// before a Decision: the caller reads context events, computes
	// a seq cutoff from the highest seq observed, runs domain logic
	// on the context, then issues AppendIfNoTagMatches with the same
	// filter and cutoff.
	//
	// Server-side this combines the same filter algebra used by
	// AppendIfNoTagMatches with a forward read of the matching seqs,
	// scoped to the DCB pseudo-stream only.
	ReadDcbContext(ctx context.Context, in *ReadDcbContextRequest, opts ...grpc.CallOption) (*ReadDcbContextResponse, error)
}

type dcbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDcbServiceClient(cc grpc.ClientConnInterface) DcbServiceClient {
	return &dcbServiceClient{cc}
}

func (c *dcbServiceClient) AppendIfNoTagMatches(ctx context.Context, in *AppendIfNoTagMatchesRequest, opts ...grpc.CallOption) (*AppendIfNoTagMatchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendIfNoTagMatchesResponse)
	err := c.cc.Invoke(ctx, DcbService_AppendIfNoTagMatches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dcbServiceClient) ReadDcbContext(ctx context.Context, in *ReadDcbContextRequest, opts ...grpc.CallOption) (*ReadDcbContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDcbContextResponse)
	err := c.cc.Invoke(ctx, DcbService_ReadDcbContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DcbServiceServer is the server API for DcbService service.
// All implementations should embed UnimplementedDcbServiceServer
// for forward compatibility.
//
// DcbService exposes the Dynamic Consistency Boundary (DCB) primitive
// of ReckonDB to polyglot clients.
//
// Where the existing StreamService.AppendEvents enforces consistency
// against a per-stream version counter (the classic event-sourcing
// optimistic concurrency model), DCB enforces consistency against a
// tag-filter context query: "no event matching this filter has been
// written since I last looked".
//
// The pattern is the cross-cutting complement to per-aggregate
// consistency. Use it when the invariant a write must preserve
// crosses streams (uniqueness, allocation, rate-limit, eligibility)
// rather than lives inside one aggregate.
//
// Requires backing ReckonDB cluster on reckon-db 3.1.1+
// (reckon_gater 2.3.1+). Older backings surface UNIMPLEMENTED.
type DcbServiceServer interface {
	// Conditionally append events under the DCB pseudo-stream.
	//
	// Server evaluates the TagFilter against the tag index. If any
	// event matching the filter has seq strictly greater than the
	// supplied seq_cutoff, the write is rejected with a Conflict
	// response carrying the highest matching seq the server observed.
	// Otherwise the events are appended atomically and Committed
	// carries the last assigned seq.
	//
	// seq_cutoff is signed: -1 means "I have seen nothing yet" and
	// ANY matching event is a conflict. A value of N (>= 0) means
	// "I saw through seq N" and only seqs strictly above N conflict.
	//
	// The conditional-append is atomic across the Ra log entry: the
	// server either commits all events or none. Partial commits do
	// not happen.
	AppendIfNoTagMatches(context.Context, *AppendIfNoTagMatchesRequest) (*AppendIfNoTagMatchesResponse, error)
	// Read events from the DCB pseudo-stream that match a TagFilter,
	// ordered by seq ascending. Use this to populate the "context"
	// before a Decision: the caller reads context events, computes
	// a seq cutoff from the highest seq observed, runs domain logic
	// on the context, then issues AppendIfNoTagMatches with the same
	// filter and cutoff.
	//
	// Server-side this combines the same filter algebra used by
	// AppendIfNoTagMatches with a forward read of the matching seqs,
	// scoped to the DCB pseudo-stream only.
	ReadDcbContext(context.Context, *ReadDcbContextRequest) (*ReadDcbContextResponse, error)
}

// UnimplementedDcbServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDcbServiceServer struct{}

func (UnimplementedDcbServiceServer) AppendIfNoTagMatches(context.Context, *AppendIfNoTagMatchesRequest) (*AppendIfNoTagMatchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendIfNoTagMatches not implemented")
}
func (UnimplementedDcbServiceServer) ReadDcbContext(context.Context, *ReadDcbContextRequest) (*ReadDcbContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDcbContext not implemented")
}
func (UnimplementedDcbServiceServer) testEmbeddedByValue() {}

// UnsafeDcbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DcbServiceServer will
// result in compilation errors.
type UnsafeDcbServiceServer interface {
	mustEmbedUnimplementedDcbServiceServer()
}

func RegisterDcbServiceServer(s grpc.ServiceRegistrar, srv DcbServiceServer) {
	// If the following call panics, it indicates UnimplementedDcbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DcbService_ServiceDesc, srv)
}

func _DcbService_AppendIfNoTagMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendIfNoTagMatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcbServiceServer).AppendIfNoTagMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcbService_AppendIfNoTagMatches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcbServiceServer).AppendIfNoTagMatches(ctx, req.(*AppendIfNoTagMatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DcbService_ReadDcbContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDcbContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DcbServiceServer).ReadDcbContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DcbService_ReadDcbContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DcbServiceServer).ReadDcbContext(ctx, req.(*ReadDcbContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DcbService_ServiceDesc is the grpc.ServiceDesc for DcbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DcbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.DcbService",
	HandlerType: (*DcbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendIfNoTagMatches",
			Handler:    _DcbService_AppendIfNoTagMatches_Handler,
		},
		{
			MethodName: "ReadDcbContext",
			Handler:    _DcbService_ReadDcbContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reckon_dcb.proto",
}
