// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: reckon_subscriptions.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Type             SubscriptionType       `protobuf:"varint,2,opt,name=type,proto3,enum=reckon.gateway.v1.SubscriptionType" json:"type,omitempty"`
	Selector         string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,4,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	StartFrom        uint64                 `protobuf:"varint,5,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	PoolSize         uint32                 `protobuf:"varint,6,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *SubscribeRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_TYPE_UNSPECIFIED
}

func (x *SubscribeRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SubscribeRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *SubscribeRequest) GetStartFrom() uint64 {
	if x != nil {
		return x.StartFrom
	}
	return 0
}

func (x *SubscribeRequest) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

type AckEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StreamId         string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,3,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	EventNumber      uint64                 `protobuf:"varint,4,opt,name=event_number,json=eventNumber,proto3" json:"event_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AckEventRequest) Reset() {
	*x = AckEventRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEventRequest) ProtoMessage() {}

func (x *AckEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEventRequest.ProtoReflect.Descriptor instead.
func (*AckEventRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *AckEventRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *AckEventRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AckEventRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *AckEventRequest) GetEventNumber() uint64 {
	if x != nil {
		return x.EventNumber
	}
	return 0
}

type CreateSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Type             SubscriptionType       `protobuf:"varint,2,opt,name=type,proto3,enum=reckon.gateway.v1.SubscriptionType" json:"type,omitempty"`
	Selector         string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,4,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	StartFrom        uint64                 `protobuf:"varint,5,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	PoolSize         uint32                 `protobuf:"varint,6,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSubscriptionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_TYPE_UNSPECIFIED
}

func (x *CreateSubscriptionRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStartFrom() uint64 {
	if x != nil {
		return x.StartFrom
	}
	return 0
}

func (x *CreateSubscriptionRequest) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

type RemoveSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Type             SubscriptionType       `protobuf:"varint,2,opt,name=type,proto3,enum=reckon.gateway.v1.SubscriptionType" json:"type,omitempty"`
	Selector         string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,4,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveSubscriptionRequest) Reset() {
	*x = RemoveSubscriptionRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionRequest) ProtoMessage() {}

func (x *RemoveSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveSubscriptionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *RemoveSubscriptionRequest) GetType() SubscriptionType {
	if x != nil {
		return x.Type
	}
	return SubscriptionType_SUBSCRIPTION_TYPE_UNSPECIFIED
}

func (x *RemoveSubscriptionRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *RemoveSubscriptionRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *ListSubscriptionsRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,2,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetSubscriptionRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

type GetSubscriptionLagRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StoreId          string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	SubscriptionName string                 `protobuf:"bytes,2,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubscriptionLagRequest) Reset() {
	*x = GetSubscriptionLagRequest{}
	mi := &file_reckon_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionLagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionLagRequest) ProtoMessage() {}

func (x *GetSubscriptionLagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionLagRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionLagRequest) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *GetSubscriptionLagRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetSubscriptionLagRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

type SubscriptionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *RecordedEvent         `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Checkpoint    uint64                 `protobuf:"varint,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionEvent) Reset() {
	*x = SubscriptionEvent{}
	mi := &file_reckon_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionEvent) ProtoMessage() {}

func (x *SubscriptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionEvent.ProtoReflect.Descriptor instead.
func (*SubscriptionEvent) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *SubscriptionEvent) GetEvent() *RecordedEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SubscriptionEvent) GetCheckpoint() uint64 {
	if x != nil {
		return x.Checkpoint
	}
	return 0
}

type AckEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEventResponse) Reset() {
	*x = AckEventResponse{}
	mi := &file_reckon_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEventResponse) ProtoMessage() {}

func (x *AckEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEventResponse.ProtoReflect.Descriptor instead.
func (*AckEventResponse) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{8}
}

type CreateSubscriptionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_reckon_subscriptions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type RemoveSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriptionResponse) Reset() {
	*x = RemoveSubscriptionResponse{}
	mi := &file_reckon_subscriptions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriptionResponse) ProtoMessage() {}

func (x *RemoveSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{10}
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*SubscriptionInfo    `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_reckon_subscriptions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{11}
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*SubscriptionInfo {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type GetSubscriptionLagResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Lag               uint64                 `protobuf:"varint,1,opt,name=lag,proto3" json:"lag,omitempty"`
	CurrentCheckpoint uint64                 `protobuf:"varint,2,opt,name=current_checkpoint,json=currentCheckpoint,proto3" json:"current_checkpoint,omitempty"`
	LatestVersion     uint64                 `protobuf:"varint,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSubscriptionLagResponse) Reset() {
	*x = GetSubscriptionLagResponse{}
	mi := &file_reckon_subscriptions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionLagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionLagResponse) ProtoMessage() {}

func (x *GetSubscriptionLagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reckon_subscriptions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionLagResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionLagResponse) Descriptor() ([]byte, []int) {
	return file_reckon_subscriptions_proto_rawDescGZIP(), []int{12}
}

func (x *GetSubscriptionLagResponse) GetLag() uint64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

func (x *GetSubscriptionLagResponse) GetCurrentCheckpoint() uint64 {
	if x != nil {
		return x.CurrentCheckpoint
	}
	return 0
}

func (x *GetSubscriptionLagResponse) GetLatestVersion() uint64 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

var File_reckon_subscriptions_proto protoreflect.FileDescriptor

const file_reckon_subscriptions_proto_rawDesc = "" +
	"\n" +
	"\x1areckon_subscriptions.proto\x12\x11reckon.gateway.v1\x1a\x13reckon_shared.proto\"\xeb\x01\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.reckon.gateway.v1.SubscriptionTypeR\x04type\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12+\n" +
	"\x11subscription_name\x18\x04 \x01(\tR\x10subscriptionName\x12\x1d\n" +
	"\n" +
	"start_from\x18\x05 \x01(\x04R\tstartFrom\x12\x1b\n" +
	"\tpool_size\x18\x06 \x01(\rR\bpoolSize\"\x99\x01\n" +
	"\x0fAckEventRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x12+\n" +
	"\x11subscription_name\x18\x03 \x01(\tR\x10subscriptionName\x12!\n" +
	"\fevent_number\x18\x04 \x01(\x04R\veventNumber\"\xf4\x01\n" +
	"\x19CreateSubscriptionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.reckon.gateway.v1.SubscriptionTypeR\x04type\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12+\n" +
	"\x11subscription_name\x18\x04 \x01(\tR\x10subscriptionName\x12\x1d\n" +
	"\n" +
	"start_from\x18\x05 \x01(\x04R\tstartFrom\x12\x1b\n" +
	"\tpool_size\x18\x06 \x01(\rR\bpoolSize\"\xb8\x01\n" +
	"\x19RemoveSubscriptionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.reckon.gateway.v1.SubscriptionTypeR\x04type\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12+\n" +
	"\x11subscription_name\x18\x04 \x01(\tR\x10subscriptionName\"5\n" +
	"\x18ListSubscriptionsRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"`\n" +
	"\x16GetSubscriptionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12+\n" +
	"\x11subscription_name\x18\x02 \x01(\tR\x10subscriptionName\"c\n" +
	"\x19GetSubscriptionLagRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12+\n" +
	"\x11subscription_name\x18\x02 \x01(\tR\x10subscriptionName\"k\n" +
	"\x11SubscriptionEvent\x126\n" +
	"\x05event\x18\x01 \x01(\v2 .reckon.gateway.v1.RecordedEventR\x05event\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\x04R\n" +
	"checkpoint\"\x12\n" +
	"\x10AckEventResponse\"E\n" +
	"\x1aCreateSubscriptionResponse\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"\x1c\n" +
	"\x1aRemoveSubscriptionResponse\"f\n" +
	"\x19ListSubscriptionsResponse\x12I\n" +
	"\rsubscriptions\x18\x01 \x03(\v2#.reckon.gateway.v1.SubscriptionInfoR\rsubscriptions\"\x84\x01\n" +
	"\x1aGetSubscriptionLagResponse\x12\x10\n" +
	"\x03lag\x18\x01 \x01(\x04R\x03lag\x12-\n" +
	"\x12current_checkpoint\x18\x02 \x01(\x04R\x11currentCheckpoint\x12%\n" +
	"\x0elatest_version\x18\x03 \x01(\x04R\rlatestVersion2\xf0\x05\n" +
	"\x13SubscriptionService\x12X\n" +
	"\tSubscribe\x12#.reckon.gateway.v1.SubscribeRequest\x1a$.reckon.gateway.v1.SubscriptionEvent0\x01\x12S\n" +
	"\bAckEvent\x12\".reckon.gateway.v1.AckEventRequest\x1a#.reckon.gateway.v1.AckEventResponse\x12q\n" +
	"\x12CreateSubscription\x12,.reckon.gateway.v1.CreateSubscriptionRequest\x1a-.reckon.gateway.v1.CreateSubscriptionResponse\x12q\n" +
	"\x12RemoveSubscription\x12,.reckon.gateway.v1.RemoveSubscriptionRequest\x1a-.reckon.gateway.v1.RemoveSubscriptionResponse\x12n\n" +
	"\x11ListSubscriptions\x12+.reckon.gateway.v1.ListSubscriptionsRequest\x1a,.reckon.gateway.v1.ListSubscriptionsResponse\x12a\n" +
	"\x0fGetSubscription\x12).reckon.gateway.v1.GetSubscriptionRequest\x1a#.reckon.gateway.v1.SubscriptionInfo\x12q\n" +
	"\x12GetSubscriptionLag\x12,.reckon.gateway.v1.GetSubscriptionLagRequest\x1a-.reckon.gateway.v1.GetSubscriptionLagResponseBCZAcodeberg.org/reckon-db-org/reckon-go/genproto/gatewayv1;gatewayv1b\x06proto3"

var (
	file_reckon_subscriptions_proto_rawDescOnce sync.Once
	file_reckon_subscriptions_proto_rawDescData []byte
)

func file_reckon_subscriptions_proto_rawDescGZIP() []byte {
	file_reckon_subscriptions_proto_rawDescOnce.Do(func() {
		file_reckon_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reckon_subscriptions_proto_rawDesc), len(file_reckon_subscriptions_proto_rawDesc)))
	})
	return file_reckon_subscriptions_proto_rawDescData
}

var file_reckon_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_reckon_subscriptions_proto_goTypes = []any{
	(*SubscribeRequest)(nil),           // 0: reckon.gateway.v1.SubscribeRequest
	(*AckEventRequest)(nil),            // 1: reckon.gateway.v1.AckEventRequest
	(*CreateSubscriptionRequest)(nil),  // 2: reckon.gateway.v1.CreateSubscriptionRequest
	(*RemoveSubscriptionRequest)(nil),  // 3: reckon.gateway.v1.RemoveSubscriptionRequest
	(*ListSubscriptionsRequest)(nil),   // 4: reckon.gateway.v1.ListSubscriptionsRequest
	(*GetSubscriptionRequest)(nil),     // 5: reckon.gateway.v1.GetSubscriptionRequest
	(*GetSubscriptionLagRequest)(nil),  // 6: reckon.gateway.v1.GetSubscriptionLagRequest
	(*SubscriptionEvent)(nil),          // 7: reckon.gateway.v1.SubscriptionEvent
	(*AckEventResponse)(nil),           // 8: reckon.gateway.v1.AckEventResponse
	(*CreateSubscriptionResponse)(nil), // 9: reckon.gateway.v1.CreateSubscriptionResponse
	(*RemoveSubscriptionResponse)(nil), // 10: reckon.gateway.v1.RemoveSubscriptionResponse
	(*ListSubscriptionsResponse)(nil),  // 11: reckon.gateway.v1.ListSubscriptionsResponse
	(*GetSubscriptionLagResponse)(nil), // 12: reckon.gateway.v1.GetSubscriptionLagResponse
	(SubscriptionType)(0),              // 13: reckon.gateway.v1.SubscriptionType
	(*RecordedEvent)(nil),              // 14: reckon.gateway.v1.RecordedEvent
	(*SubscriptionInfo)(nil),           // 15: reckon.gateway.v1.SubscriptionInfo
}
var file_reckon_subscriptions_proto_depIdxs = []int32{
	13, // 0: reckon.gateway.v1.SubscribeRequest.type:type_name -> reckon.gateway.v1.SubscriptionType
	13, // 1: reckon.gateway.v1.CreateSubscriptionRequest.type:type_name -> reckon.gateway.v1.SubscriptionType
	13, // 2: reckon.gateway.v1.RemoveSubscriptionRequest.type:type_name -> reckon.gateway.v1.SubscriptionType
	14, // 3: reckon.gateway.v1.SubscriptionEvent.event:type_name -> reckon.gateway.v1.RecordedEvent
	15, // 4: reckon.gateway.v1.ListSubscriptionsResponse.subscriptions:type_name -> reckon.gateway.v1.SubscriptionInfo
	0,  // 5: reckon.gateway.v1.SubscriptionService.Subscribe:input_type -> reckon.gateway.v1.SubscribeRequest
	1,  // 6: reckon.gateway.v1.SubscriptionService.AckEvent:input_type -> reckon.gateway.v1.AckEventRequest
	2,  // 7: reckon.gateway.v1.SubscriptionService.CreateSubscription:input_type -> reckon.gateway.v1.CreateSubscriptionRequest
	3,  // 8: reckon.gateway.v1.SubscriptionService.RemoveSubscription:input_type -> reckon.gateway.v1.RemoveSubscriptionRequest
	4,  // 9: reckon.gateway.v1.SubscriptionService.ListSubscriptions:input_type -> reckon.gateway.v1.ListSubscriptionsRequest
	5,  // 10: reckon.gateway.v1.SubscriptionService.GetSubscription:input_type -> reckon.gateway.v1.GetSubscriptionRequest
	6,  // 11: reckon.gateway.v1.SubscriptionService.GetSubscriptionLag:input_type -> reckon.gateway.v1.GetSubscriptionLagRequest
	7,  // 12: reckon.gateway.v1.SubscriptionService.Subscribe:output_type -> reckon.gateway.v1.SubscriptionEvent
	8,  // 13: reckon.gateway.v1.SubscriptionService.AckEvent:output_type -> reckon.gateway.v1.AckEventResponse
	9,  // 14: reckon.gateway.v1.SubscriptionService.CreateSubscription:output_type -> reckon.gateway.v1.CreateSubscriptionResponse
	10, // 15: reckon.gateway.v1.SubscriptionService.RemoveSubscription:output_type -> reckon.gateway.v1.RemoveSubscriptionResponse
	11, // 16: reckon.gateway.v1.SubscriptionService.ListSubscriptions:output_type -> reckon.gateway.v1.ListSubscriptionsResponse
	15, // 17: reckon.gateway.v1.SubscriptionService.GetSubscription:output_type -> reckon.gateway.v1.SubscriptionInfo
	12, // 18: reckon.gateway.v1.SubscriptionService.GetSubscriptionLag:output_type -> reckon.gateway.v1.GetSubscriptionLagResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_reckon_subscriptions_proto_init() }
func file_reckon_subscriptions_proto_init() {
	if File_reckon_subscriptions_proto != nil {
		return
	}
	file_reckon_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reckon_subscriptions_proto_rawDesc), len(file_reckon_subscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reckon_subscriptions_proto_goTypes,
		DependencyIndexes: file_reckon_subscriptions_proto_depIdxs,
		MessageInfos:      file_reckon_subscriptions_proto_msgTypes,
	}.Build()
	File_reckon_subscriptions_proto = out.File
	file_reckon_subscriptions_proto_goTypes = nil
	file_reckon_subscriptions_proto_depIdxs = nil
}
