// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: reckon_stores.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoresService_ListStores_FullMethodName  = "/reckon.gateway.v1.StoresService/ListStores"
	StoresService_GetStore_FullMethodName    = "/reckon.gateway.v1.StoresService/GetStore"
	StoresService_WatchStores_FullMethodName = "/reckon.gateway.v1.StoresService/WatchStores"
)

// StoresServiceClient is the client API for StoresService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StoresService — store DISCOVERY, not management.
//
// Stores in reckon-db are ephemeral: they exist when their supervision
// tree is running on at least one cluster node, and disappear when the
// last running instance terminates. There is no CreateStore / DeleteStore.
// Lifecycle is owned by deployment tooling (sys.config, hecate-gitops,
// systemd units), the same primitive that bootstraps `default_store`.
//
// This service is the public surface for "what stores currently exist
// in the cluster, and where", suitable for SDKs, TUIs, admin UIs, and
// observability tooling.
type StoresServiceClient interface {
	// List all stores currently announced anywhere in the cluster.
	// Returns one entry per (store_id, node) pair — a store running on
	// 4 nodes appears 4 times. Client groups by store_id if it wants
	// a single logical view.
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	// Get the entries for a specific store (one per node currently
	// hosting it). Returns NOT_FOUND if no node is announcing it.
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error)
	// Server-stream of cluster topology changes for stores. Emits a
	// STORE_ANNOUNCED event for each currently-known entry (snapshot),
	// then live STORE_ANNOUNCED / STORE_RETIRED events as stores come
	// and go. Closes when the client disconnects.
	WatchStores(ctx context.Context, in *WatchStoresRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoreEvent], error)
}

type storesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoresServiceClient(cc grpc.ClientConnInterface) StoresServiceClient {
	return &storesServiceClient{cc}
}

func (c *storesServiceClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, StoresService_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreResponse)
	err := c.cc.Invoke(ctx, StoresService_GetStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) WatchStores(ctx context.Context, in *WatchStoresRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoreEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoresService_ServiceDesc.Streams[0], StoresService_WatchStores_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStoresRequest, StoreEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoresService_WatchStoresClient = grpc.ServerStreamingClient[StoreEvent]

// StoresServiceServer is the server API for StoresService service.
// All implementations should embed UnimplementedStoresServiceServer
// for forward compatibility.
//
// StoresService — store DISCOVERY, not management.
//
// Stores in reckon-db are ephemeral: they exist when their supervision
// tree is running on at least one cluster node, and disappear when the
// last running instance terminates. There is no CreateStore / DeleteStore.
// Lifecycle is owned by deployment tooling (sys.config, hecate-gitops,
// systemd units), the same primitive that bootstraps `default_store`.
//
// This service is the public surface for "what stores currently exist
// in the cluster, and where", suitable for SDKs, TUIs, admin UIs, and
// observability tooling.
type StoresServiceServer interface {
	// List all stores currently announced anywhere in the cluster.
	// Returns one entry per (store_id, node) pair — a store running on
	// 4 nodes appears 4 times. Client groups by store_id if it wants
	// a single logical view.
	ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	// Get the entries for a specific store (one per node currently
	// hosting it). Returns NOT_FOUND if no node is announcing it.
	GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error)
	// Server-stream of cluster topology changes for stores. Emits a
	// STORE_ANNOUNCED event for each currently-known entry (snapshot),
	// then live STORE_ANNOUNCED / STORE_RETIRED events as stores come
	// and go. Closes when the client disconnects.
	WatchStores(*WatchStoresRequest, grpc.ServerStreamingServer[StoreEvent]) error
}

// UnimplementedStoresServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoresServiceServer struct{}

func (UnimplementedStoresServiceServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedStoresServiceServer) GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedStoresServiceServer) WatchStores(*WatchStoresRequest, grpc.ServerStreamingServer[StoreEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchStores not implemented")
}
func (UnimplementedStoresServiceServer) testEmbeddedByValue() {}

// UnsafeStoresServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoresServiceServer will
// result in compilation errors.
type UnsafeStoresServiceServer interface {
	mustEmbedUnimplementedStoresServiceServer()
}

func RegisterStoresServiceServer(s grpc.ServiceRegistrar, srv StoresServiceServer) {
	// If the following call panics, it indicates UnimplementedStoresServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoresService_ServiceDesc, srv)
}

func _StoresService_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoresService_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoresService_GetStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_WatchStores_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStoresRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoresServiceServer).WatchStores(m, &grpc.GenericServerStream[WatchStoresRequest, StoreEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoresService_WatchStoresServer = grpc.ServerStreamingServer[StoreEvent]

// StoresService_ServiceDesc is the grpc.ServiceDesc for StoresService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoresService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reckon.gateway.v1.StoresService",
	HandlerType: (*StoresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStores",
			Handler:    _StoresService_ListStores_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _StoresService_GetStore_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStores",
			Handler:       _StoresService_WatchStores_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reckon_stores.proto",
}
